### ISSUE TITLE
Turn off some warnings, like "Passive Voice Misuse", and "inconsistent spelling" for British English

### ISSUE THREAD

**Issue by sebastian-ruiz** [znck/grammarly#10]
It would be great to have the option to turn off some of the warnings of like `Passive Voice Misuse`. 

Secondly, I get errors for `inconsistent spelling` when typing in British English. I have British English as my default in Grammarly.com preferences. It would be good to have the option to set British English as an option in the settings page.

Thank you for the work so far!

**Comment by znck** [comment]
<img width="675" alt="Screenshot 2019-12-18 at 11 17 02 AM" src="https://user-images.githubusercontent.com/2596484/71059079-ec7ae500-2187-11ea-8fd0-7821848b418a.png">
