### ISSUE TITLE
Command 'grammarly.set-credentials' not found

### ISSUE THREAD

**Issue by vikramkhatri** [znck/grammarly#101]
I installed the latest plug-in. The VSCode version is 1.40.1 on Mac.

When I try to provide login, it throws an error: Command 'grammarly.set-credentials' not found

Any tip?

**Comment by Surgbc** [comment]
@vikramkhatri the latest version of the Grammarly extension(0.12.1) goes not install in vs code version 1.40. It will install version 0.9  of the plugin. Try upgrading vs code to the latest version.
