### ISSUE TITLE
Extension unpublished

### ISSUE THREAD

**Issue by d-asensio** [znck/grammarly#104]
Hi, the extension appears as unpublished.

![image](https://user-images.githubusercontent.com/13970905/81395027-35c1d600-9123-11ea-9f3f-d333d2116d13.png)

**Comment by fuzihaofzh** [comment]
If it is possible to provide the vsix file for install? Seems cannot install directly from the marketplace. Thanks for your great work.

**Comment by lizequn** [comment]
Hi, 
Thanks for providing this useful tool. Just want to know why it is unpublished? 
is that ok/allowed to package vsix file ourselves for personal usage?

**Comment by znck** [comment]
I am not sure what happened here. The extension is unpublished and locked (I can't republish too). There's no communication from VS Code Marketplace about unpublishing. I have emailed to support.

**Comment by LucaMarconato** [comment]
Hello, any update?

**Comment by znck** [comment]
The extension has been removed on request from Grammarly. I am discussing with the Grammarly team and figuring out how to get it back.

**Comment by niem94** [comment]
@znck hope you figure it out. This extension is super useful, and promising!

**Comment by thomaskrause** [comment]
@znck Also a big "thank you" for the extension and I hope it will be resolved. It really has been essential in my daily workflow. Meanwhile, I canceled my Grammarly subscription and mentioned the removal of this extension as the cause.

**Comment by d-asensio** [comment]
Hi, @znck  any update on this? I can help with development effort if needed ;)

**Comment by LucaMarconato** [comment]
@znck until you get an answer I can only speculate about the reason of the removal, so here it is my thought. I have not look at your implementation but I can guess that your extension could lead to a large increase in volume of requests per person. Maybe changing the code to minimise syntax checks, by performing them only on requests, on new code and only on text (non-symbols) parts, could make the tool suitable to come back online.

**Comment by znck** [comment]
Main reason is trademark violation. I was in contact with Grammarly engineering team and they’re very supportive and they’re too surprised when the extension was taken down. I am trying to figure out what is the exact violation and how to avoid it.

**Comment by vincekruger** [comment]
Man Grammarly is being a dick.   If they allow this extension and support for it, boom, there is my money for an account as is the case I think with many other developers.

I will spend some time this weekend to see I can get this working with text strings in js, ts and dart.

**Comment by dKab** [comment]
I would subscribe for Grammarly if it was available for VSCode since VSCode is my main tool for writing.  Hope this gets resolved soon.

**Comment by EntilZha** [comment]
I’m unfamiliar with the code, but one alternative would be to replace grammarly with LanguageTool (or make it work for either). There are a few such extensions on the marketplace, but I don’t think they work as well/are still maintained. The grammar checking probably isn’t as good, but might be good enough

**Comment by AdrianoCahete** [comment]
> Main reason is trademark violation.

@znck Change the extension name to anything more "generic" and try to republish again.

**Comment by adriaanvanrossum** [comment]
To others who want to install this extension:

1. Download the `.vsix` file via [releases/tag/v0.12.2](https://github.com/znck/grammarly/releases/tag/v0.12.2)
2. Go to Extensions in VS Code and hit the three dots and select "Install from VSIX":
  <kbd><img width="686" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/83770464-62650100-a681-11ea-8c38-bad3938c749f.png"></kbd>
3. Thank @znck for writing this plugin

**Comment by mddanishyusuf** [comment]
I install the plugin and doesn't seem working for me.

**Comment by MarcoScaletta** [comment]
@adriaanvanrossum 
`.vsix` is the best solution so far.
It works for me! 
Thanks

**Comment by eriklieben** [comment]
Also have a premium subscription to Grammarly. 

@grammarly could you reconsider allowing this extension?

**Comment by ChrisChinchilla** [comment]
Great extension! Also consider Vale as an alternative, but it lacks the "smarts" of Grammarly, but is very configurable. We're working on maybe adding some of that NLP magic… Slowly.

**Comment by bakulaibuji** [comment]
> Great extension! Also consider Vale as an alternative, but it lacks the "smarts" of Grammarly, but is very configurable. We're working on maybe adding some of that NLP magic… Slowly.

Hey! I had installed this extension while had a problem. Loginning with grammarly account, it indicated that "authication requires captcha input". DId you met the same situation?

**Comment by ahmadawais** [comment]
Grammarly doesn't have an extension. I requested one several times. It was about time you created this awesome extension that I also recommend in my [VSCode.pro](https://VSCode.pro) course. @grammarly reconsider allowing this extension?

**Comment by selfagency** [comment]
@grammarly seriously, work something out here

**Comment by d-asensio** [comment]
@garmmarly any update on this so far?

**Comment by znck** [comment]
Finally, published again. 😌 Now I can focus on other issues.

**Comment by amitguptagwl** [comment]
@znck I'm just wondered about data security. What if I open a file which contains some user id and password, will this extension share the data with the server? Can I make the use of this plugin on demand/click?

**Comment by znck** [comment]
The plugin can be used on demand, there’s a setting for that.
