### ISSUE TITLE
Captcha requirement when authenticating

### ISSUE THREAD

**Issue by jaredmorgs** [znck/grammarly#107]
![image](https://user-images.githubusercontent.com/952793/85081350-154f6600-b20f-11ea-8ccb-4e293ecd743f.png)

------------------

**UPDATE:**

This requires support from the Grammarly Auth team. They have already implemented the necessary changes and waiting for release _(which is delayed due to holidays)_. Expecting this to be resolved in the first half of Jan 2020. 🥂

**Comment by bakulaibuji** [comment]
I also met the same question.

**Comment by diegosucaria** [comment]
The same is happening here!

**Comment by ahmadawais** [comment]
Same thing there. Locked out 
![image](https://user-images.githubusercontent.com/960133/85976086-2e1c0080-b9f3-11ea-9db8-0054016804ff.png)

**Comment by bakulaibuji** [comment]
It is sad without using this extension. Is there a way to resolve this question?

**Comment by a-n-d-i-p-y** [comment]
Same problem here. Went fine until about 5 hours ago.

**Comment by efracondes** [comment]
Same problem here :(

**Comment by stderr-enst** [comment]
Same here.
Is this related to the number of API requests and having a free and not a premium account or something?

**Comment by ahmadawais** [comment]
This has been resolved. Download the latest release from the GitHub https://github.com/znck/grammarly/releases and install via vsix

**Comment by ahmadawais** [comment]
@znck I just updated the ext to 0.12.5 and the captcha issue is back :(

**Comment by znck** [comment]
I’ll address CAPTCHA issue soon. I’ll start working at Grammarly next month and internal knowledge would help to fix these tricky issues. ✌️

**Comment by bakulaibuji** [comment]
@znck It's happy to see you again. And we will wait for your next released version.

**Comment by ahmadawais** [comment]
Thank you @znck — I rebooted to change my IP. Now I was able to login without captcha warning. Also the `Grammarly null` error was resolved. Thank you :)

**Comment by jgrigera** [comment]
@znck this seems to have reappeared (see #125, #127). Maybe the extension could try showing the captcha to the user to keep Grammarly happy?

**Comment by Maltilum** [comment]
Yeah. This is happening to me as well. It was working fine when I installed it a week or two ago. Now I'm somewhat sad because I was really enjoying being actually able to use VS code to write markdown docs.

**Comment by jgrigera** [comment]
BTW, it seems that the firefox plugin calls this endpoint: "api/login/captcha-verify" with { "googleReCaptchaToken": xxx}
Not sure were it gets the captcha from though...

**Comment by matherm** [comment]
@ahmadawais How exactly could you manage to sign-in without the captcha? I restarted my internet router several times and also tried a VPN service. Nothing helped to overcome the captcha.

**Comment by boazbk** [comment]
Looking forward to a resolution of this. 
p.s.  @znck congrats on working on grammarly! As a paid subscriber I'm very happy with them, though would appreciate if they could support markdown and latex (basically by just knowing what to ignore).

**Comment by jbaruch** [comment]
Another :+1: on 0.12.5

**Comment by codeHatcher** [comment]
also having this issue

**Comment by bakulaibuji** [comment]
A easy way to solve this question is to use a VPN service.

**Comment by craigsansam** [comment]
I am also facing this issue.

**Comment by faguado-uvigo** [comment]
> A easy way to solve this question is to use a VPN service.

Can you elaborate more? Just connect to a VPN?? Thanks

**Comment by faguado-uvigo** [comment]
> > A easy way to solve this question is to use a VPN service.
> 
> Can you elaborate more? Just connect to a VPN?? Thanks

I have a fixed IP and I continue having this issue. I've also tried with the VPN service that I use and even the VPN that I use in the university ... The same problem. Can you help us?

**Comment by codeHatcher** [comment]
VPN didn't help me either

**Comment by majorgearhead** [comment]
Tried VPN and changing IP's here and none of this worked.  I think at this point if the login could render the captcha box this would solve the issue.

**Comment by vyskoczilova** [comment]
Hi @znck @ahmadawais  could you give us a hint on how to log in? The captcha issue is still present, no matter what I try to do and I'm logged into Grammarly account when trying to sign up in VS Code.

**Comment by jdrew1303** [comment]
Hey 🙋🏻‍♂️

There may be a weird hack that you could use to enable this while waiting for a full fix. It might be possible to let a user take the auth/CSRF token from the cookie in their browser. This seems to be what the chrome plugin is doing. 

<img width="1439" alt="Screenshot_29_09_2020__23_55" src="https://user-images.githubusercontent.com/2535432/94626112-50534200-02b2-11eb-86d0-bea554ffd218.png">

In this case, the user would log in as normal. Then go into: `dev tools ->  application tab -> cookies`. Take the auth and CSRF from the cookie and use them as the credentials. Like I said previously it's not a good fix but it may be a temporary fix until a web view or the like can be added. 

The other alternative is to snoop on the android/iphone app HTTP calls using a proxy and see how it bypasses captcha.

**Comment by diegosucaria** [comment]
@jdrew1303 could you ellaborate a little bit more please?

Just tried using the grauth value as username and csrf-token value as password and I still get the same "auth requires captcha" message

Thanks!

**Comment by jdrew1303** [comment]
Hey @diegosucaria 

Apologies for the confusion. I meant this for @znck as a potential temporary fix that would be quicker to implement instead of rendering the captcha. It doesn't work at the moment.

Sorry I should have been more explicit about this. 🙈

**Comment by matherm** [comment]
> The other alternative is to snoop on the android/iphone app HTTP calls using a proxy and see how it bypasses captcha.

I tried. But, unfortunately I couldn't inject the proxy certificate to break up the HTTPS encryption, because of client certificate validation.

Is the Chrome Plugin really still working?

**Comment by amacgregor** [comment]
Same issue here

**Comment by zhyhan** [comment]
Encounter the same issue too.

**Comment by znck** [comment]
UPDATE: Grammarly auth team has included this captcha issue in the current sprint. Hopefully max 2 more weeks of this captcha madness.

**Comment by yordis** [comment]
Sorry had to do it!

![image](https://user-images.githubusercontent.com/4237280/100187355-c9c77500-2e9c-11eb-9798-22213de00965.png)

**Comment by yordis** [comment]
@znck does Grammarly provides OAuth2 or some sort of protocol that would allow you to open a browser tab, and get some sort of token back to the VSCode extension?

**Comment by znck** [comment]
Yep, the extension would be using oauth similar to the Grammarly App.

**Comment by Kalaschnik** [comment]
@znck Any news on this?

**Comment by pauloribeiro-codacy** [comment]
According to https://github.com/znck/grammarly/issues/125#issuecomment-738548342 there should be a fix soon. Great news!

**Comment by ms3056** [comment]
Would love a fix for this. Definitely will send a coffee someone's way if it is resolved.

**Comment by marcoaaguiar** [comment]
It would be nice to have this issue (or #125) pinned given the number of duplicates new issues being posted (#127, #123, #134, #147)

**Comment by amacgregor** [comment]
No updates yet?

**Comment by AkibAzmain** [comment]
Any alternatives of this extension?

**Comment by danielepolencic** [comment]
Is there any workaround?
Or is it possible to patch the code to show the captcha?

https://github.com/znck/grammarly/blob/1093e4b51c1fec0e626c77b7f3647c03ca910e25/packages/grammarly-api/src/auth.ts#L223

If the response contains the challenge, maybe we could display the image and make it work.

**Comment by christopher-buss** [comment]
Thank you 💕 I can now login.

**Comment by amacgregor** [comment]
The overlays still want you to login

Allan MacGregor
Senior Software Engineer

P: +1 (647) 916-3590 (tel:+1%20(647)%20916-3590)
W: http://allanmacgregor.com (https://link.getmailspring.com/link/7AE7001C-AFF0-4D52-B6C1-FF635677870A@getmailspring.com/0?redirect=http%3A%2F%2Fallanmacgregor.com&recipient=cmVwbHkrQUFCVFpTTk1DNUNNU1RWTlVWRzJYTEY2Q1hJMzNFVkJOSEhDTVBSSUJZQHJlcGx5LmdpdGh1Yi5jb20%3D)

Book Time to Chat (https://link.getmailspring.com/link/7AE7001C-AFF0-4D52-B6C1-FF635677870A@getmailspring.com/3?redirect=https%3A%2F%2Fcalendly.com%2Fallanmacgregor&recipient=cmVwbHkrQUFCVFpTTk1DNUNNU1RWTlVWRzJYTEY2Q1hJMzNFVkJOSEhDTVBSSUJZQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by bjaggi** [comment]
so many requests and still waiting for the fix?, i am one of them!

**Comment by amacgregor** [comment]
This was fixed already

Allan MacGregor
Senior Software Engineer

Book Time to Chat ***@***.***/0?redirect=https%3A%2F%2Fcalendly.com%2Fallanmacgregor&recipient=cmVwbHkrQUFCVFpTUEhWR0pOS0ZWTFJJR05XSU42TklJWkxFVkJOSEhDTVBSSUJZQHJlcGx5LmdpdGh1Yi5jb20%3D)
+1 (647) 916-3590 (tel:+1%20(647)%20916-3590)
allanmacgregor.com ***@***.***/1?redirect=http%3A%2F%2Fallanmacgregor.com&recipient=cmVwbHkrQUFCVFpTUEhWR0pOS0ZWTFJJR05XSU42TklJWkxFVkJOSEhDTVBSSUJZQHJlcGx5LmdpdGh1Yi5jb20%3D)

I'm building a micro-saas to help people monitor and keep their sites secure, you can learn more at: siteguardian.dev ***@***.***/4?redirect=https%3A%2F%2Fsiteguardian.dev&recipient=cmVwbHkrQUFCVFpTUEhWR0pOS0ZWTFJJR05XSU42TklJWkxFVkJOSEhDTVBSSUJZQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by bjaggi** [comment]
v0.12.5 is still giving me the same problem on VS Code
