### ISSUE TITLE
Feature request: default severity

### ISSUE THREAD

**Issue by hperrot** [znck/grammarly#115]
Could we add a default severity to the config?
This would help to go through all suggestions, not only the ones which are actively set to another severity than "Hint".
"Information", "Warning", and "Error" are compiled in the problems tab, but not the "Hint" annotations.

**Comment by bakulaibuji** [comment]
I want change my severity setting for grammarly extension, but it does not work. Is there someone who konw what happened?

**Comment by mwiesnero2c** [comment]
When can we expect the next release including this feature? It seems to be implemented quite some time ago.

**Comment by jlperla** [comment]
I also am having trouble with it.  I am willing to copy some text to do it for all types, but I can't find the full list of settings in the docs.
