### ISSUE TITLE
*Italic* text followed by a footnote in Markdown incorrectly interpreted

### ISSUE THREAD

**Issue by NeoTheThird** [znck/grammarly#118]
I ran into an issue where italic text is not properly interpreted as part of the sentence when followed by a footnote. Example:

![image](https://user-images.githubusercontent.com/12068939/88692001-dc53bc80-d0fd-11ea-8536-18b99d9bb359.png)

The first occurance of `An *Nginx* server configuration is prepared...` is correctly interpreted, while `An *Nginx*^[some footnote] server configuration is prepared...` is incorrectly marked as **The use of a versus an**.

**Comment by felixfbecker** [comment]
It seems that generally any markdown syntax, like links with `[]` confuses Grammarly. It would be great if the extension could spell check a "rendered" version of the markdown instead of the source, and map the errors back to the source code.
