### ISSUE TITLE
Remove file extension restrictions.

### ISSUE THREAD

**Issue by Jan-Karasinski** [znck/grammarly#126]
There are various files, that can contain plain text (for example embedded documentation in source files).
In my opinion, this extension should be allowed to run on every file, regardless of its extension and it should be up to the users to decide whether they are ok with false errors.

**Comment by trepagnier** [comment]
@Jan-Karasinski Thank you!! Will give it a shot.

**Comment by Jan-Karasinski** [comment]
Found a cleaner way to remove this check - go to `C:\Users\user\.vscode\extensions\znck.grammarly-0.14.0\dist\extension\index.js:46936` and remove `!LANGUAGES.includes(languageId) || `

**Comment by cjduncana** [comment]
If it could at least check my comments, it would be great.

**Comment by Avivhdr** [comment]
Where can I find this file on a mac computer?
