### ISSUE TITLE
Authentication requires captcha input 

### ISSUE THREAD

**Issue by ALIENQuake** [znck/grammarly#127]
![image](https://user-images.githubusercontent.com/365255/90976411-21241500-e53d-11ea-9bcf-7c05781105e3.png)

I have the same issue as #123 but the problem doesn't go away.

**Comment by guillemf** [comment]
The same is happening to me. Requesting captcha input.

**Comment by jgrigera** [comment]
Seems a duplicate of #123 and #107

**Comment by ALIENQuake** [comment]
duplicate of #123 and #107
