### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by BioHazard1282** [znck/grammarly#132]
How can I log in to my Grammarly account? The gif doesn't show much on how

**Comment by booyaa** [comment]
Use command palette to run: `Grammarly: Login to grammarly.com`.

FYI this feature is broken because Grammarly has added Captcha to trip up 3rd party use.

#107 #125

**Comment by pwinston** [comment]
So basically the extension is not usuable? Or it's usable for free features only?

**Comment by znck** [comment]
Free features for now. Fix in progress.

**Comment by seb-ast** [comment]
It would be great to have a possibility to login into the paid account using Apple ID.

**Comment by HanlongLiao** [comment]
> It would be great to have a possibility to login into the paid account using Apple ID.

Does it mean if the Grammarly  ID is APPlE ID (iCloud email ), then it will be OK?

**Comment by seb-ast** [comment]
It is more than that I think as iCloud is an identity provider for Grammarly account with all of 2fa on the way.
