### ISSUE TITLE
Set document goals: Emotion picker items mismatched

### ISSUE THREAD

**Issue by LinqLover** [znck/grammarly#133]
![image](https://user-images.githubusercontent.com/38782922/94042147-7d43b880-fdcb-11ea-927b-bf480baa46b6.png)

The order does not match.

**Comment by bsridatta** [comment]
Is this extension ever working? Can you share how you manage to login in vscode with captcha?

**Comment by LinqLover** [comment]
@bsridatta I can't log in because of #18, but I still can see a percent score in the status bar of VS code.

**Comment by jaguarfi** [comment]
I think this issue was already solved in the commit https://github.com/znck/grammarly/commit/45864a225031e72b1538d806e329bcf32749ab69. So I guess that the next version will fix that problem.
