### ISSUE TITLE
'retry grammar check' no checking is done

### ISSUE THREAD

**Issue by david-loe** [znck/grammarly#136]
When opening a file 'retry grammar check' is shown in the Status Bar, clicking doesn't change anything.
![image](https://user-images.githubusercontent.com/56305409/98220645-e3853480-1f4e-11eb-8d04-fb8afcbfcb83.png)

When I start to type something the message changes to 'anonymous calculating...' but also nothing happens.
Sometimes it says: 'Grammarly needs at least 30 words [...]', although my files have far more than that.
Sometimes there are categories like 'clarity' but all with 0, and also nothing changes over time.

I've tried different versions, and reinstalled grammarly multiple times, but nothing helped.
Maybe it's because I'm behind a proxy?

System:
Windows 10
VS Code 1.50.1
using a proxy

**Comment by znck** [comment]
Cannot reproduce this issue. If problem still exists, open another issue with steps to reproduce.
