### ISSUE TITLE
Install and run the LSP only

### ISSUE THREAD

**Issue by gianarb** [znck/grammarly#137]
Hello

Very cool project! I was looking for something like this but I am not a vscode user. I read that you implemented this extension as a language server. I am wondering if you can point me to how I can get only the server up and running without the actual extension because technically it can be reused with other language server clients in other editors.

I am curious to try the LSP with vim.

Thanks

**Comment by znck** [comment]
LSP source code is contained in [src/server](https://github.com/znck/grammarly/tree/master/src/server), though the API is considered internal and it is very likely to change in the future (there's a major rewrite in progress).

**Comment by gianarb** [comment]
I got the language server running with vim-coc (language server-client for vim), when a markdown file gets open but I am not able to communicate with the server properly, when I run the Diagnostic action nothing really happens.

I will close this issue for now and I will keep looking at this problem to see if I can get something good out of it. My personal suggestion is to keep the LSP as agnostic as possible from code. In theory, it should be its own application, in this way also other editors will enjoy your great work!

Have a good weekend!

**Comment by znck** [comment]
Makes sense to make it reusable. (will look into it)

**Comment by gianarb** [comment]
(if you need any help let me know I am looking by myself to see if I can get the server making something useful in vim)

**Comment by znck** [comment]
If you use this, base your solution from next branch.

**Comment by gianarb** [comment]
Yep, I am currently trying to use this language server with vim, I will switch to `next`, thanks
