### ISSUE TITLE
Exclude folders (like node_modules)

### ISSUE THREAD

**Issue by Epistol** [znck/grammarly#14]
Grammarly works well in vscode ... too well : can't open my node_modules folder without triggerring billions of alert from Grammarly !

**Comment by carlos-algms** [comment]
+1
It would be nice to have a config key to exclude any number of folders.
Node_modules would be great to have as a default exclusion.  
Also, like other extensions, respect `.gitignore` exclusions.

**Comment by znck** [comment]
Added a ignore list (which includes `node_modules` by default). 

> Using `.gitignore` would require more work, create a separate issue if needed.
