### ISSUE TITLE
Shortcut for jumping to previous/next error.

### ISSUE THREAD

**Issue by albert-ying** [znck/grammarly#143]
Hi, I'm wonder is there any shortcut to move the cursor to the next phrase with grammar issue? 

For example, F8 in vs code is moving to the next error, it works for spelling errors (with red underline) but it doesn't jump to other forms of grammar errors (denoted by grey text). 

Is there any universal way to navigate across issues identified by Grammarly? Thank you!

**Comment by znck** [comment]
You can use `⌥ + F8` to "go to the next problem".

**Comment by kevindekemele** [comment]
This doesn't work. They grey is very hard too say, can this color be changed?

**Comment by m4x74** [comment]
For Windows it is Shift+F8...
