### ISSUE TITLE
Feature Request: Support Oauth login

### ISSUE THREAD

**Issue by sjkillen** [znck/grammarly#144]
If you created your Grammarly account using an Oauth service such as Google, Grammarly does not offer a way for you to log in to your account without this service. It would be nice to have some way of logging in via a browser window.
Could potentially fix #107 and #125 as well.

**Comment by drexlerd** [comment]
Hi, you can contact grammarly to change the login schema to email+password directly without using google services

**Comment by znck** [comment]
I have requested Grammarly for an oauth client id. I was hoping getting this in December but with holidays approaching,seems improbable. By Jan, I guess.

**Comment by desert0616** [comment]
any luck?

**Comment by znck** [comment]
I'm feeling lucky tomorrow.
