### ISSUE TITLE
Authentication requires captcha input

### ISSUE THREAD

**Issue by HanlongLiao** [znck/grammarly#147]
![1](https://user-images.githubusercontent.com/38033498/103090292-a32b6400-462b-11eb-820c-78c118f8d4ec.png)

The version is 0.12.5

**Comment by 5c0t-qi** [comment]
Duplicate of #125

**Comment by YuvrajKhavad** [comment]
Yes, I have the same error, Because grammarly.com add google captcha for login.

**Comment by znck** [comment]
Duplicate of #107
