### ISSUE TITLE
enable on restructured text (rst files)

### ISSUE THREAD

**Issue by grst** [znck/grammarly#15]
When I try to run the grammarly extension on [restructuredtext](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) files, I get the error

> Command 'Grammarly: Check grammar errors' is not enabled in the current context.

Could you enable the extension for `rst` files? 
Or maybe more general, make it configurable on which languages the extension should be executed.

**Comment by znck** [comment]
I don't know how to make the languages configurable. I have to read about that. For now, I am including `rst` files in configuration.

**Comment by Surendrajat** [comment]
@znck This does not work yet and throws `The .rst filetype is not supported`. I had to add `.rst` to the list of Languages myself to make working.

**Comment by edxu96** [comment]
@Surendrajat Hi, could you please elaborate on "add `.rst` to the list of Languages myself to make working"? I cannot find the option to do that.

**Comment by Surendrajat** [comment]
@edxu96 I cloned this repo and edited the file that contains the list of file types(forgot which one) and built the extension myself.

**Comment by edxu96** [comment]
Got it. Sounds challenging for me ... Thanks for the reply
