### ISSUE TITLE
Incomplete quick-fix suggestions

### ISSUE THREAD

**Issue by suhaibmujahid** [znck/grammarly#151]
Currently, after the lase update (v0.13.0), the fix suggestions do not show the fix. For example, it will tell you that there is a spelling mistake without showing what is the correct spelling until you apply the fix.

### It used to look like this:

![image](https://user-images.githubusercontent.com/4151357/105222106-05db2700-5b28-11eb-98e2-30db53709b99.png)

### This what looks now
![image](https://user-images.githubusercontent.com/4151357/105222303-5488c100-5b28-11eb-9834-b494ab595554.png)

**Comment by Alimektor** [comment]
I confirmed this information. I use earlier version and it works fine.

**Comment by znck** [comment]
I think it's a regression from refactoring. Will fix it ASAP.

**Comment by suhaibmujahid** [comment]
Thank you @znck, looking forward. Please let me know if I can help.
