### ISSUE TITLE
Commands other than login and logout aren't working

### ISSUE THREAD

**Issue by richt3211** [znck/grammarly#152]
Booted up VSCode today and the commands for Grammarly other than login and logout aren't working. When I try to use the command palette to run a command such as grammarly.check, no commands show up. 

Here's a screenshot. 
<img width="632" alt="Screen Shot 2021-01-20 at 2 45 00 PM" src="https://user-images.githubusercontent.com/19878922/105244716-25754e00-5b2e-11eb-9ea3-0a567d8747eb.png">

**Comment by Alimektor** [comment]
I confirmed this information. I use _earlier_ version and it works fine.

**Comment by znck** [comment]
Thanks for reporting, will fix it ASAP.

**Comment by hadim** [comment]
Same here. I can't add word to a dict anymore.
