### ISSUE TITLE
Take too much space of the status bar

### ISSUE THREAD

**Issue by BIKA-C** [znck/grammarly#153]
The extension displays the email address on the status bar, and it covers a big area of the bar.
It would be nice if there is an option to not display the email address or display the user name instead

**Comment by BerriJ** [comment]
As most people only have one Grammarly account it would probably be sufficient to just add a little person icon beside the score to tell the user that this score was calculated using the personal Grammarly account. Alternatively, the login details could be included in the hover info.

**Comment by znck** [comment]
Added a setting to hide username from status bar.
