### ISSUE TITLE
Using quick fix on multiple consecutive errors may cause those to be fixed in the wrong place

### ISSUE THREAD

**Issue by amargs** [znck/grammarly#154]
When having more than one error in the text, after using the quick fix to solve the first error, the following one gets "misaligned", which results in the auto fix for that second error also "shifting" accordingly.

As an example, writing these two sentences which have misspelled words:
![image](https://user-images.githubusercontent.com/17692221/105627037-117e6480-5e2c-11eb-9097-33b74d443cd2.png)

After applying the quick fix on the first sentence, you can see the underline in the second sentence "shifted":
![image](https://user-images.githubusercontent.com/17692221/105627079-691cd000-5e2c-11eb-9511-234d94173185.png)

Which cause the quick fix on the second sentence to be wrong:
![image](https://user-images.githubusercontent.com/17692221/105627097-7df96380-5e2c-11eb-8768-7bbb59d70c49.png)

If I force Grammarly to run spell check again after the first quick fix, the second one would then be adjusted correctly, but that is not practical when you have a large document with several errors.

I've tried this in a different machine with those same sentences and was able to reproduce the problem, but I cannot find the pattern that triggers this behaviour. For example, if instead of having dialect set to British, I had it as American or Australian, the quick fix would work fine for both errors (it would be replaced with "misspelled" instead of "misspelt", and it would not "eat" any characters). However, I tried different sentences with errors and this problem did not always show.
I tried this same example a third time in a machine in which the extension was still in the previous version. It was difficult because sometimes, after I applied the quick fix on the first sentence, suddenly the second sentence no longer had a quick fix, even though it previously had one. After a few tries of rewriting those sentences, I was able to apply the quick fix for both of them, and this problem did not arise, both were fixed in the right place.

**Comment by suhaibmujahid** [comment]
I can confirm that I faced the same issue.
