### ISSUE TITLE
Error in LaTeX description, Code: -32603, textDocument/codeAction failed

### ISSUE THREAD

**Issue by RonaldErnst** [znck/grammarly#156]
Following error occurs whenever I hover over a marked segment inside an item of a description of a LaTeX document.
```
[Error - 12:33:32] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```

![grafik](https://user-images.githubusercontent.com/39799257/105840382-3eb94700-5fd3-11eb-9bed-283fc5078695.png)

Also, I don't know if this should be a seperate issue, but there are no more quick fixes anymore. In the previous versions 0.12.x the analysis of the text wasn't as detailed but there were more suggested quick fixes.

**Comment by znck** [comment]
Could you share a text sample to reproduce this issue?

**Comment by RonaldErnst** [comment]
Sorry, of course. As shown in the image I linked above the error appears when i hover over "Relevance" or any other word inside the brackets.

```
\begin{description}
    \item[Relevance] revolves around the meaningfulness of the results and the amount and depth of relevant information for a consumer.
    It also is arguably the most important feature of a benchmark.
    \item[Reproducibility] is the ability to achieve the same outcome consistently.
    Optimally, this would ensure perfect consistency if unpredictable factors like scheduling or network delays wouldn't add complexity to the system. 
    Hence why every benchmark comes with a certain amount of variability. This issue can be addressed by including multiple runs for a metric.
    \item[Fairness] guarantees that all systems can participate in a benchmark without constraints.
    \item[Verifiability] specifies the confidence of the results produced by the benchmark.
    This attribute can be improved by either letting the benchmark control the configuration, self-validate the workload, or by including more details in the result than necessary.
    \item[Usability] describes the ease of installing and running the benchmark. Self-validation also helps with this feature because the results don't have to be verified manually.
\end{description}
```

**Comment by jpdias** [comment]
I'm having the exactly same issue. I don't know if related, but it is happening (as reported) with LaTeX documents.

**Comment by ashudeep** [comment]
Same issue. Hovering over the error shows the notification for the error. 

Does someone have an idea how to disable this specific error?

**Comment by SebastianElvis** [comment]
Same here. A workaround seems to be clearing the output in VSCode's output panel. After I cleared the output panel the issue disappeared.
