### ISSUE TITLE
Ability to suppress certain Grammarly checks

### ISSUE THREAD

**Issue by p-ang** [znck/grammarly#158]
Would it be possible to include a setting that would allow users to suppress certain Grammarly rules, such as the passive voice check?

**Comment by fredguth** [comment]
I hate passive voice check as well, I also have contacted Grammarly to allow us to disable passive voice checking.

**Comment by a-kazakov** [comment]
As a temporary workaround I edited the extension's source code locally and that helped. Open `%USERPROFILE%\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js`, search for `diagnostics.set(alert.id, this.toDiagnostics(alert, document))`, and wrap it into any condition. I did the following
```
if (!alert.title.includes("Passive voice")) {
    diagnostics.set(alert.id, this.toDiagnostics(alert, document));
}
```
