### ISSUE TITLE
Cannot login in Grammarly Pro from popup editor tip (wrong link)

### ISSUE THREAD

**Issue by donangel** [znck/grammarly#163]
OS: MacOS Catalina (10.15.7 (19H15))

Browsers: I tried with Microsoft Edge (my browser of preference) and Chrome (before submitting this here).

The problem: Visual Studio Code does not seem to identify that I'm a logged-in Pro user. It always asks for logging in, and when I click the "Login" link, it just opens the extension's page, which... well, shows that I'm logged on. I tried to log off and log in but without success.

Any advice?

**Comment by TheBigoranger** [comment]
Me too, any ideas about how to login and activate the premium mode?

**Comment by TheBigoranger** [comment]
I figured it out, well, just in my case. I am a Windows OS user, so goodluck~

The autocorrection redirects you to the official website [https://www.grammarly.com/signin](url)
But actually, what you need to use is to run the VScode command(press F1):  and type in _grammarly.login_.
It will redirect you to another website other than the official one. After you log in to that website, it will ask you to go back to the VScode which means you will be logged in at VScode.
Restart the VScode and you will find out that you have been logged in.
BTW, the logout command also needs to restart the VScode.

A suggestion to the developer: can you guys add a note in the readme file telling people not to click the login URL that Grammarly autocorrection offers but instead to run the grammarly.login command? I think more people will find it confusing that clicking the official login button but didn't work out.
A huge hug to you guys for making such a wonderful plugin!

**Comment by donangel** [comment]
Great tip! Thank you very much! It fixed it for me.

I think this is a bug, and it may need fixing. But your tip is an excellent workaround.

**Comment by thomnico** [comment]
Have the same issue, but F1 does not work on MacOs .. did someone find out a solution on Mac ??

**Comment by fuyuk** [comment]
Fn+F1 may assign as F1 on your Mac.  You can also use command+shift+p to show the VScode command palette. 

Input a command  "Grammarly: Login to Grammarly.com",  while the VScode status line shows "anonymous". The Grammarly login page automatically shows up on your browser and log in as a premium account. This page will try to open VScode, and when you press OK, VSCode will display the message "Logged in as your premium account name". Note that the status line still shows "anonymous" at this time. After restarting VScode, your account will appear in the status line, and all functions will be available.

Enjoy!

**Comment by thomnico** [comment]
Workaround works for me thanks for the tip to a newbie on vscode :) 

The "login" link in the event does not work though

**Comment by MarkWoulfeNeo4j** [comment]
> Fn+F1 may assign as F1 on your Mac. You can also use command+shift+p to show the VScode command palette.
> 
> Input a command "Grammarly: Login to Grammarly.com", while the VScode status line shows "anonymous". The Grammarly login page automatically shows up on your browser and log in as a premium account. This page will try to open VScode, and when you press OK, VSCode will display the message "Logged in as your premium account name". Note that the status line still shows "anonymous" at this time. After restarting VScode, your account will appear in the status line, and all functions will be available.
> 
> Enjoy!

This works fine for me right up until the point I restart VScode, I just get an endless spinning icon next to my login account and it never loads.

**Comment by natalyjazzviolin** [comment]
> > Fn+F1 may assign as F1 on your Mac. You can also use command+shift+p to show the VScode command palette.
> > Input a command "Grammarly: Login to Grammarly.com", while the VScode status line shows "anonymous". The Grammarly login page automatically shows up on your browser and log in as a premium account. This page will try to open VScode, and when you press OK, VSCode will display the message "Logged in as your premium account name". Note that the status line still shows "anonymous" at this time. After restarting VScode, your account will appear in the status line, and all functions will be available.
> > Enjoy!
> 
> This works fine for me right up until the point I restart VScode, I just get an endless spinning icon next to my login account email and it never loads.
> 
> ![image](https://user-images.githubusercontent.com/82045391/117164660-bbbb4000-adbc-11eb-9913-f80bc89b50f3.png)

The login worked for me on Windows, but also getting endless spinning after restarting VSCode.

**Comment by sbwww** [comment]
> I figured it out, well, just in my case. I am a Windows OS user, so goodluck~
> 
> The autocorrection redirects you to the official website [https://www.grammarly.com/signin](url) But actually, what you need to use is to run the VScode command(press F1): and type in _grammarly.login_. It will redirect you to another website other than the official one. After you log in to that website, it will ask you to go back to the VScode and if you see that, you will be logged in at VScode. Restart the VScode and you will find out that you have been logged in. BTW, the logout command also needs to restart the VScode.
> 
> A suggestion to the developer: can you guys add a note in the readme file telling people not to click the login URL that Grammarly autocorrection offers but instead to run the grammarly.login command? I think more people will find it confusing that clicking the official login button but didn't work out. A huge hug to you guys for making such a wonderful plugin!

That is to say, to reload vscode after any operation related to the account I guess. Really saved my day!

**Comment by 55199789** [comment]
> 

Same problem for me. Have you figured it out? Thanks!

**Comment by 55199789** [comment]
> > > Fn+F1 may assign as F1 on your Mac. You can also use command+shift+p to show the VScode command palette.
> > > Input a command "Grammarly: Login to Grammarly.com", while the VScode status line shows "anonymous". The Grammarly login page automatically shows up on your browser and log in as a premium account. This page will try to open VScode, and when you press OK, VSCode will display the message "Logged in as your premium account name". Note that the status line still shows "anonymous" at this time. After restarting VScode, your account will appear in the status line, and all functions will be available.
> > > Enjoy!
> > 
> > 
> > This works fine for me right up until the point I restart VScode, I just get an endless spinning icon next to my login account email and it never loads.
> > ![image](https://user-images.githubusercontent.com/82045391/117164660-bbbb4000-adbc-11eb-9913-f80bc89b50f3.png)
> 
> The login worked for me on Windows, but also getting endless spinning after restarting VSCode.

Same problem for me. Have you figured it out? Thanks!
