### ISSUE TITLE
Login error when using VSCodium

### ISSUE THREAD

**Issue by himekifee** [znck/grammarly#170]
Sorry for bothering you; I understand `vscodium` is not supported by this extension. I do have a pretty good experience with this extension until I log in to my account. Firstly it reports an error about `vscodium` is not a supported scheme, so I added an entry for it into `CLIENTS` array with `vscodium: 'extensionVSCodium',`. However, It is still not working with an error

```	
        at /home/grider/.vscode-oss/extensions/znck.grammarly-0.14.0/dist/extension/index.js:48681:58
	at new Promise (<anonymous>)
```
Which is when it searches for cookies. Before that, I already logged in with my username and password through an externally opened web page. Is there a way to bypass this issue? Thanks.

**Comment by himekifee** [comment]
Never mind, seems `extensionVSCodium` is not a valid token for Grammarly. Changed to `extensionVSCode`, and ran `vscodium --no-sandbox --open-url "vscode://znck.grammarly/auth/callback?code=blahblahblah` and it worked.

**Comment by leon-erd** [comment]
@himekifee Hey could you maybe explain in a bit more detail how you did it I'm facing the same problem. What do you mean by changing to `extensionVSCode` and where did you get that link from `vscode://znck.grammarly/auth/callback?code=blahblahblah`? I assume that you just ran the command from the terminal. Thanks already!

**Comment by himekifee** [comment]
Sorry, it has been a while so I don't quite remember the detail. For the later link part, that is generated from the Grammarly web page, it will try to summon a desktop application but vscodium does not really follow that `vscode://` scheme so you need to manually summon that by the above command. I'm not quite sure how to make the `CLIENT` part working.

**Comment by leon-erd** [comment]
So run the `Grammarly: Login command` in VSCodium and then my browser comes up with the Grammarly connection page. I click confirm and then I get a "The address wasn’t understood" error in Firefox and nothing happens. With Chrome I get an `about:blank` page and it asks me if I want to open VSCodium - URL Handler. But then also nothing happens. I don't really understand how you got that link especially the `code=blahblahblah` part :D

**Comment by himekifee** [comment]
That URL handler page should have a URL just like `vscode://znck.grammarly/auth/callback?code=blahblahblah`. Substitute that into `vscodium --no-sandbox --open-url "vscode://znck.grammarly/auth/callback?code=blahblahblah"`. This should be run in the terminal.

**Comment by leon-erd** [comment]
Okay I just made it!!! In the firefox link that didn't work there was indeed a part `code=...`. I just copied it and replaced it in the command that you posted above and now it worked. Thanks a lot for ur help and for opening this issue!!!

**Comment by leon-erd** [comment]
The format of the firefox page was `https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect?code=123`. It only worked with the syntax you posted `vscode://znck.grammarly/auth/callback?code=123`
