### ISSUE TITLE
Category name no longer displayed on hover of a problem

### ISSUE THREAD

**Issue by svilches** [znck/grammarly#172]
I am trying to configure the severity of some categories, and for that I need to know the category name used by Grammarly. 

According to the [guide](https://github.com/znck/grammarly#configuring-alert-severity)  on GitHub, the category name should be displayed when hovering on a problem.
However, it seems not to be present in v0.14:

![image](https://user-images.githubusercontent.com/1826396/110594586-472da180-817d-11eb-9338-c709f01240a5.png)

(the category name should appear where the red arrow is)

As a possible alternative solution: where could I find a list of all Grammarly error categories?

Thanks!

**Comment by svilches** [comment]
I found a workaround: when Grammarly Debugging is on (_"grammarly.debug": true_), the category name can be found in the hover text:
![image](https://user-images.githubusercontent.com/1826396/110933895-9b778380-832d-11eb-98c9-9335ec7ac04e.png)

**Comment by beyefendi** [comment]
@svilches can you managed to suppress information warnings via severity configuration.
Still producing informational errors and highlighting errors on text as well.
![image](https://user-images.githubusercontent.com/7609852/116720599-b3d65700-a9dc-11eb-95fd-3ac89ec15f40.png)
