### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by OpoOpo** [znck/grammarly#177]
Hi, when I type `ctrl+p` and then `>Grammarly :login to grammarly.com` I got an error that says:
```
Command 'Grammarly: Login to grammarly.com' resulted in an error 
(Running the contributed command: 'grammarly.login' failed.)
```

Thank you

**Comment by tcinbis** [comment]
Same here :(

**Comment by MLackner** [comment]
I had similar issues with VSCode v1.54. Solved it by downgrading to v1.53.2.

**Comment by achimcc** [comment]
In my case, after entering the Login command, it is asking:

`Do you want to open the external website?`

**Comment by albert-ying** [comment]
Same here, in my case, it just never finishes loading in the status bar

<img width="239" alt="image" src="https://user-images.githubusercontent.com/59846322/116476017-a0928280-a848-11eb-8a13-2c1b69ef290f.png">

**Comment by ronijaakkola** [comment]
For me, it just opens the website. Logging in on the website does nothing and the plugin still asks me to login in Code.

**Comment by MaxOSchulte** [comment]
Having this issue in Code v 1.55 downgrade to 1.54.3 resolved it for me

**Comment by MarkWoulfeNeo4j** [comment]
> Same here, in my case, it just never finishes loading in the status bar
> 
> <img alt="image" width="239" src="https://user-images.githubusercontent.com/59846322/116476017-a0928280-a848-11eb-8a13-2c1b69ef290f.png">

I am getting this same issue

**Comment by mxstbr** [comment]
Same issue here:

<img width="289" alt="Screenshot 2021-06-24 at 11 07 29" src="https://user-images.githubusercontent.com/7525670/123235844-88ec1900-d4dc-11eb-8de5-90a2fab24c73.png">
