### ISSUE TITLE
Doesn't work even after Login

### ISSUE THREAD

**Issue by ghost** [znck/grammarly#178]
I have logged in to the account, still in VS Code it asks me to login?

**Comment by albert-ying** [comment]
Same problem here. Seems that it could not connect to the server and never start to check for grammar.

**Comment by IsaacRWangPhysics** [comment]
Same here

**Comment by ikraamg** [comment]
I had to reload VS code and the request to login stopped displaying.

**Comment by byteSamurai** [comment]
Just got the same problem, what it fixed for me:
- logout
- login
- restarting vs code, just reloading was not enough.
@albert-ying  and @quarkquartet does this work for you?

**Comment by albert-ying** [comment]
@byteSamurai It works for me now.

What I did is log out first, then restart, then log in again.
