### ISSUE TITLE
Command to stop the extension not found

### ISSUE THREAD

**Issue by Josee9988** [znck/grammarly#181]
The extension says it has 5 commands:
![image](https://user-images.githubusercontent.com/38838976/114295522-1905ef00-9aa6-11eb-9d68-27ee6a63927c.png)

But I could only find 2, I would like to use the stop Grammarly command but I don't know where it could be.
![image](https://user-images.githubusercontent.com/38838976/114295509-0a1f3c80-9aa6-11eb-9316-c8dec4309761.png)

**Comment by meEvelyn** [comment]
I have the same issue and I cannot find settings for this extension.
![image](https://user-images.githubusercontent.com/83519409/116796495-d636a600-aaaa-11eb-85e8-96e7cfbd2b8b.png)
