### ISSUE TITLE
Publish extension to Open VSX

### ISSUE THREAD

**Issue by artbird309** [znck/grammarly#184]
Per issue 2237 on Code-server (https://github.com/cdr/code-server/issues/2237#issuecomment-818041200) they are switching the extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/) can this extension published to Open VSX?

**Comment by DavidSilva98** [comment]
This would also be pretty useful for VSCodium users as its default extension registry is [Open VSX](https://open-vsx.org/). The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions), in case it is needed.

**Comment by znck** [comment]
Done. https://open-vsx.org/extension/znck/grammarly
