### ISSUE TITLE
single newlines are treated as full newlines causing lost of false positives

### ISSUE THREAD

**Issue by ssbarnea** [znck/grammarly#188]
This extension is almost impossible to use with Markdown documents because it will generate a huje number of false positive results on sentences that spread on multiple lines.

Most people writing markdown use a line wrapping at 79-120 column as markdown does consider single newlines as continuation, only double newlines act as real newline.

Example below would trigger an error about missing article on cat, when in fact the article is there.
```
... The
cat is out of the bag.
```

In fact the same problem applies not only to markdown but also to plain text and rst files, on any of them is normal
to wrap sentences on multiple lines.

**Comment by Zehelein** [comment]
Yes, this would be really important to have. Otherwise, it is a really wonderful addition but for markdown, Asciidoc, etc. it is very hard to use.

**Comment by oweidner** [comment]
In addition to the "Missing Article" errors described above, I also get a lot of "Incorrect Spacing" errors in indented blocks when using hard line wraps in my LaTeX documents:

```
23 Blah blah: 
24     [...]                                  It shows how the system can be
25     integrated with HPC system architectures and how it enables     [...]
```

In the case above, `be integrated` is flagged as "Incorrect Spacing".

**Comment by ssbarnea** [comment]
Sadly as of today I am forced to add `**/*.md` to the exclude list due to this bug and likely to uninstall it as markdown and rst linting was the most useful place to use it, typos in source code being less likely to happen.

**Comment by ssbarnea** [comment]
My joy lasted few seconds after reading "mark as completed". 

I wanted to implement stale bot myself but that alone is a case against using it.

**Comment by znck** [comment]
This should be fixed. If not, please create a new issue.

**Comment by ssbarnea** [comment]
@znck Thanks! I updated to pre-release and I confirm that Grammarly appears to be working fine now.

**Comment by onichandame** [comment]
@znck I am experiencing the same issue with mdx files even with pre-release. It would be nice if the fix can be applied to all filetypes
