### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by michaelschufi** [znck/grammarly#189]
Hi

After successfully authenticating a notification tells me that I am logged in, showing my name.
However, the status bar shows that I am logged in as `anonymous`.

Also, some issues show the text "👉 Login to get automated fix for this issue.", which is confusing and suggests something went wrong:
![image](https://user-images.githubusercontent.com/2805598/120020541-23466300-bfea-11eb-8788-9fc63d38f97e.png)

Note: I don't have a premium account on Grammarly yet.

**Comment by nakulpadalkar** [comment]
I have a similar problem. While "anonymous" plugin detects issues in the given text, once I log in with my credentials plugin keeps searching for issues in the text but never gives any suggestions.

**Comment by michaelschufi** [comment]
@znck Do you have any idea what the problem could be? Since the login overall seems to be working (notification works), I'm hopeful, that it isn't a big issue :)

**Comment by thomnico** [comment]
I have the same issue here. Once logged the little spinning on left of my login name (in status bar) keep spinning and I receive zero recommendations, whereas I got some in anonymous. 

Tried without second step authentication but did not change anything. This makes the extension unusable for me :(

**Comment by fredgrott** [comment]
I know why this shows up. How many of you Grammarly users are using the free account and not premium?

I can very that this issue shows up when using Grammarly free accounts. I still get the correct Grammarly score and the correct Grammarly hints, however.

**Comment by nakulpadalkar** [comment]
> I know why this shows up. How many of you Grammarly users are using the free account and not premium?
> 
> I can very that this issue shows up when using Grammarly free accounts. I still get the correct Grammarly score and the correct Grammarly hints, however.

Not really, I am a Grammarly premium user. I get the grammar corrections (with all the bells and whistles) when I am logged out, but as soon as I sign back in the issue persists.

**Comment by akira-t** [comment]
In my case, after upgrading Grammarly to premium and logging in, I still got "👉 Login to get automated fix for this issue." I re-installed the extension and that fixed it!

**Comment by thomnico** [comment]
> In my case, after upgrading Grammarly to premium and logging in, I still got " Login to get automated fix for this issue." I re-installed the extension and that fixed it!

Works for me too save my day !!

**Comment by madcapnmckay** [comment]
To fix this I had to do the following

- CMD + Shift + P
- Type Grammarly
- Run "Grammarly: login to grammarly.com"
- Authenticate your account
- Restart VSCode
