### ISSUE TITLE
Manually disable specific types of hints

### ISSUE THREAD

**Issue by j-reher** [znck/grammarly#192]
In the Grammarly online interface I can, for example, disable marking passive voice, but that does not seem to apply within vs code. It would be great to have an option to do that.

I imagine with the grammarly.severity option existing, it might be easy to add a fifth option that fully disables a category?

**Comment by EmpireJones** [comment]
I just ran into this same issue, and agree that supporting this would be very useful! 👍

**Comment by vzaliva** [comment]
I am also very much interested in this feature
