### ISSUE TITLE
Ignore markdown frontmatter

### ISSUE THREAD

**Issue by qinyiyao** [znck/grammarly#194]
<img width="511" alt="Screen Shot 2021-06-24 at 1 31 42 AM" src="https://user-images.githubusercontent.com/6311717/123230278-eefc8000-d48b-11eb-9ec0-1dc67b4b767c.png">

It would be great if the plugin can ignore frontmatter **keys** but keep tracking the **values**.

---

(Amazing Project! 👍)

**Comment by lloydjatkinson** [comment]
This is still badly needed

**Comment by the-simian** [comment]
I saw a discussion about this here: https://github.com/znck/grammarly/discussions/282

Is there a way we could re-expose the diagnostics or supply some sort of regex-matcher? The plugin works excellently on the body text but misbehaves in the frontmatter and codeblocks in .md, .rmd, .qmd files
