### ISSUE TITLE
Personal dictionary not honored during spell check

### ISSUE THREAD

**Issue by mcecode** [znck/grammarly#195]
Hi! Thanks for the awesome extension, it's been great, but lately the personal dictionary is not being honored when spellings are being checked. I'm not sure if it's a bug or if I'm doing something wrong but I've tried reinstalling the extension and putting the `grammarly.userWords` settings in both the global and workspace specific settings but it still doesn't work.

I'm running the latest version (v0.14.0) of the extension.

Here's my current VS Code environment:

- Version: 1.57.1 (system setup)
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.18363

Below are screen shots of the error and my relevant user settings:

![grammarly-1](https://user-images.githubusercontent.com/65783406/123558200-97318200-d7c7-11eb-8c0b-4a01200d53a5.png)
![grammarly-2](https://user-images.githubusercontent.com/65783406/123558205-9bf63600-d7c7-11eb-988e-c04d72f35b4e.png)

**Comment by shrimansoft** [comment]
I have the same problem.

**Comment by Xevvy** [comment]
Same issue here. No matter what I do, the entries in my user dictionary are not respected. v0.14

**Comment by AymericBr** [comment]
Facing the same issue with v0.14.0

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by jani** [comment]
Unless I misunderstand the code, the issue is with the function isKnownWord() in grammarly/packages/grammarly-language-server/src/services/DictionaryService.ts or modules it depends on, e.g. that this.configuration.settings.userWords is always empty in the scope of the dictionary service. Maybe that helps someone more knowledgeable with this kind of coding?

**Comment by mattorp** [comment]
The ability to disable spell check from Grammarly would be great as well. Plenty of extensions are focused particularly on this and already include common programming words in their dictionary.
