### ISSUE TITLE
Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zzj0402** [znck/grammarly#196]
```
[Error - 7:45:43 pm] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```

**Comment by kieranbd** [comment]
Also having this problem in VS Code on Mac. It appears to highlight errors correctly, but as soon as I start typing it goes crazy trying to analyse every new character and the app becomes unusable - can't even type it hangs so much. Super frustrating.

**Comment by jayliu50** [comment]
Same issue on WSL while editing a .mdx file:

```
[Error - 8:48:03 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
  ```
  
It doesn't seem to be locking up my interface though, but that sounds miserable.

**Comment by ognjenio** [comment]
It seems to me that it's got something to do with escaping quotation signs. 

For instance, in a markdown file I've got the following in the frontmatter:

```highlight: "\"It's a shame.\""```

Removing that line stops the error from happening.

**Comment by lirook** [comment]
Happens to me with words that have `'` in them (such as don't).
MacOS, extension version v0.14.0.

**Comment by universemaster** [comment]
I get this error for `Text inconsistencies Grammarly(20)` see #214

**Comment by kodamok** [comment]
I have the same issue here :(

Request textDocument/codeAction failed.
  Message: Unhandled method onWorkspaceConfigForDocumentRequest
  Code: -32601

**Comment by kwinHoney** [comment]
I have the same issue here :(
[Error - 11:35:26 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603

**Comment by kwinHoney** [comment]
您的来信我已收到！

**Comment by charlielito** [comment]
Same error here in a Docker container running ubuntu20.04

**Comment by kwinHoney** [comment]
您的来信我已收到！

**Comment by znck** [comment]
Stale #232

**Comment by kwinHoney** [comment]
您的来信我已收到！
