### ISSUE TITLE
The .fountain filetype is not supported

### ISSUE THREAD

**Issue by thegreentimtam** [znck/grammarly#198]
I write screenplays using the Fountain markup language and the Better Fountain extension for VS Code.

Grammarly is not working with my screenplays, and when I enter the command "Grammarly > Check Grammar Errors" I get "The .fountain filetype is not supported."

**Comment by Avivhdr** [comment]
Hey @thegreentimtam,
You can check this issue --> #126.  If you have a windows computer you can disable it.
I have the same problem with `js` & `tsx` files but I have macOS so I'm not sure how to override this restriction. 

@znck, what is the solution on mac machines?

**Comment by sinkec** [comment]
Search text in C:\Users\user\.vscode\extensions\znck.grammarly-0.14.0\dist\extension\index.js

This is an array:

`const LANGUAGES = [
    'asciidoc',
    'git-commit',
    'git-rebase',
    'json',
    'latex',
    'markdown',
    'mdx',
    'plaintext',
    'restructuredtext',
];`

Edit it to:
`const LANGUAGES = [
    'asciidoc',
    'git-commit',
    'git-rebase',
    'json',
    'latex',
    'markdown',
    'mdx',
    'plaintext',
    'restructuredtext',
    'fountain',
];`

This solved the issue with *.fountain files for me.

**Comment by znck** [comment]
Follow https://github.com/znck/grammarly#adding-support-for-new-language to add a new language.

There are no language restrictions now, you have to opt-in by adding file name patterns:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/2596484/167086827-7d172a54-8dca-411e-a01d-8e53c0be9192.png">
