### ISSUE TITLE
Better installation experience with example settings

### ISSUE THREAD

**Issue by miohtama** [znck/grammarly#20]
I really love this extension, very good work! 

I have some suggestion to make new users to get faster up-to-speed with the extension. Maybe README can supply sample settings.json for copy-pasting, possible values and more background what the setting does.

E.g. 

* What Grammarly username/password is used for and where are they stored
* What options there are settings like `dialect`, `audience` etc. 

if you could provide me with some pointers where I can this information, I am happy to do a PR to make README better.

**Comment by znck** [comment]
Would love a PR. 

username/password for logging into grammarly.com to enable paid features like advanced grammar issues. 

dialect, audience etc to set document goals, can use overrides to set goals for specific files (can use glob pattern to match files). Exactly same as Get Goals on grammarly.com UI. 

ignore to skip files, can use glob patterns

**Comment by miohtama** [comment]
Where is the list of (multichoice?) values I can have in dialect and audience field?

**Comment by znck** [comment]
In package.json

**Comment by znck** [comment]
Related: https://github.com/microsoft/vscode/issues/95186
