### ISSUE TITLE
no instalation instructions

### ISSUE THREAD

**Issue by diekhans** [znck/grammarly#200]
I want to use this fascinating package with the emacs lsp-grammarly package.   However, there are not instructions for installing it.  I suspect this is obvious to vscode users, just not to the rest of us.

Please add instructions on how to install.

**Comment by jcs090218** [comment]
@diekhans There are documents from `lsp-mode`, see https://emacs-lsp.github.io/lsp-mode/page/lsp-grammarly/.

You can also do `M-x lsp-install-server`.
