### ISSUE TITLE
No browser is open for OAuth on Code Server

### ISSUE THREAD

**Issue by Haetsal-Lee** [znck/grammarly#201]
This issue is related to [Code Server](https://github.com/cdr/code-server).

For the case of "clone from Github" for Oauth, the new browser tab is open.

But for the Grammarly plugin, no browser tab is open for OAuth, but the following error message is shown:
```
Command 'Grammarly: Login to grammarly.com' resulted in an error (Running the contributed command: 'grammarly.login' failed.)
```

**Comment by luisherranz** [comment]
Same problem here ✋

**Comment by znck** [comment]
Update to version 0.18.0 or higher
