### ISSUE TITLE
Support github.dev

### ISSUE THREAD

**Issue by LinqLover** [znck/grammarly#202]
This is an awesome extension, and I would love to see this working in github.dev, too. I use Grammarly quite frequently for spell-checking my readmes, and in recent times, I often edit readmes by pressing <kbd>.</kbd> on GitHub.

Depending on whether this project uses any external binaries or the file system, or just is a TypeScript-only solution, this could be either something simple like adjusting the `package.json` or a rather complicated migration project. But this would be great! :-)

**Comment by znck** [comment]
There's a browser build in v0.16 (though it's untested).

**Comment by znck** [comment]
![2022-05-10 16 39 12](https://user-images.githubusercontent.com/2596484/167741837-5d2cf34b-53ff-487e-a88a-23ac1dd6dd4d.gif)
