### ISSUE TITLE
Enable grammarly not working

### ISSUE THREAD

**Issue by JuanCabre** [znck/grammarly#204]
Hello, since the last update of VSCode, the Grammarly plugin is not working for me. I am logged in as a premium user. The login works correctly. However, when I press "Enable Grammarly" at the bottom bar, the plugin does not check the document. It is stuck trying to enable the checking. One can see the loading spinning wheel and my email account at the bottom bar. The wheel just keeps spinning, and the document is not checked.

Thanks in advance for the support.

**Comment by JuanCabre** [comment]
After writing this, I turned on the debug mode in the plugin. That fixed the issue for some reason. I turned the debug mode off again, and it still works correctly. I'm glad it's working once more :)

**Comment by steliostss** [comment]
I have the same issue, suddenly it stopped working and it is stuck at loading.
I uninstalled and re-installed the extension, enabled debug mode but I still have this issue.
