### ISSUE TITLE
Next steps; Use Grammarly official API

### ISSUE THREAD

**Issue by znck** [znck/grammarly#206]
I am working on [Grammarly for developers](https://developer.grammarly.com), our first project was to build a web embedable SDK for editors and we shipped it today. Next, we'll work to support nodejs environment like vscode extension. 

Over coming months, this vscode extension would get full Grammarly support; stay tuned!

**Comment by NightMachinary** [comment]
Is the API usable with the free version?

**Comment by znck** [comment]
Yes

**Comment by vzaliva** [comment]
I am interested in helping. Please let me know how I can participate.
I am primarily interested in using Grammarly under emacs.

**Comment by flikteoh** [comment]
Is this project still active or no longer maintained?

**Comment by marianhlavac** [comment]
Obviously dead, the extension doesn't ever work anyome.

**Comment by dcervenkov** [comment]
The extension works fine for me.

**Comment by znck** [comment]
I am on the team building [official Grammarly SDK](https://developer.grammarly.com) and this extension will get major updates when official SDK for nodejs is available, likely to happen in second half of 2022. Until then this project is on halt and will receive only fixes for critical issues.

**Comment by zyrikby** [comment]
It seems that today the plugin stopped working. Here is the log:

```
(node:38576) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (/home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38903:19)
    at GrammarlyClient._queueOrSend (/home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38978:18)
    at /home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (/home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38874:16)
    at GrammarlyClient.start (/home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39160:21)
    at GrammarlyClient.onConnection [as _onConnection] (/home/yury/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39809:32)
```

Should I report this as a new issue?

**Comment by iqfareez** [comment]
@zyrikby maybe similar as #183 & #218

**Comment by zyrikby** [comment]
@iqfareez Thanks, now it works back!

**Comment by The-Periodic-Table-Of-Elements** [comment]
ok

**Comment by Firsh** [comment]
If you need a tester I'm here to help. I used to write code tutorials with WordPress but I want to move to blogs built by SSGs that are based on md with mdx - but I need Grammarly and other tools like readability and SEO checkers. Showing snippets and extending the content with custom "blocks" is a bit cumbersome when you are not in an editor like VS Code. In some context it's not even a choice, like if you were building a docs site with mkdocs, you probably still want to grammar check your writing. So I'm eagerly waiting for the official API to roll out so I can finally focus on writing only in markdown, and only in VS Code.

**Comment by theluke** [comment]
I am a volunteer too if you need a tester, I even think I can get my employer to chip in and pay some money to speed up the development

**Comment by znck** [comment]
@vzaliva If someone is interested in looking into recent issues, I can help them in getting started with the codebase.

**Comment by znck** [comment]
Done. #232
