### ISSUE TITLE
Shrink upgrade notifications

### ISSUE THREAD

**Issue by LinqLover** [znck/grammarly#209]
Too often I see the following when hovering a Grammarly warning:

![image](https://user-images.githubusercontent.com/38782922/135720623-e6511c4b-e934-4afd-a446-2130df3eb43c.png)

As I won't pay for Grammarly, this prominent hint does not help me; it is waste. Would it be possible to turn these hints off via configuration? :-)

**Comment by znck** [comment]
Open for PRs to remove this or add a configuration to hide.

**Comment by znck** [comment]
Removed in #232
