### ISSUE TITLE
Login command fails

### ISSUE THREAD

**Issue by shinjitumala** [znck/grammarly#210]
When I use the command `Grammarly: Login to grammarly.com`, the plugin complains of an error and refuses to proceed.

![image](https://user-images.githubusercontent.com/30512876/135941934-371d1ff2-f465-4bd5-9f54-46ac3014b8a4.png)

There were no logs in the Output tab.

Since I haven't seen any similar issue within the tab, I guess this has something to do with using the OSS version of vscode.

**Comment by 29antonioac** [comment]
I have the same issue using the OSS version, too. Could we get some support with this, please? Maybe there's a workaround to make this work?

Thanks in advance! The extension looks great :grin:

**Comment by mchrupczalski** [comment]
Nope, non OSS version, same error.

VSCode version: 1.61.2
Extension version: 0.14.0

![image](https://user-images.githubusercontent.com/31902386/139600362-0b87092c-18c2-4c58-8459-98431ca25d59.png)

**Comment by mkotsollaris** [comment]
Same here. Does the plugin support login?
Getting this even if I am logged in in the dashboard 
<img width="611" alt="Screen Shot 2022-01-02 at 4 56 51 PM" src="https://user-images.githubusercontent.com/8595514/147893763-62504978-90df-49fe-be16-1c53fd425af1.png">

**Comment by mchrupczalski** [comment]
> Same here. Does the plugin support login?
> Getting this even if I am logged in in the dashboard 
> <img width="611" alt="Screen Shot 2022-01-02 at 4 56 51 PM" src="https://user-images.githubusercontent.com/8595514/147893763-62504978-90df-49fe-be16-1c53fd425af1.png">
> 

It used to work in the past.

**Comment by leoseccia** [comment]
Clicking on login just opens the grammarly webpage and login does not work.

When I login via the command bar, it logs in fine but then I still get the `Login to get automated fix for this issue` message...

**Comment by kapooramit** [comment]
Yeah - it logins using command palette command but still show "Login" message so premium still not working...

**Comment by znck** [comment]
Please update extension to version 0.18.0 or higher.
