### ISSUE TITLE
Not getting any suggestions

### ISSUE THREAD

**Issue by Stephan-Brandt** [znck/grammarly#212]
Once I log in (this works) and click on enable, there is no response and the spinner keeps going for eternity.

All other grammarly services and extensions work, I have tested it in multiple networks.
To the best of my knowledge I have not changed anything since it worked last.

Neither reinstalling the extension, nor vscode had any impact.

I tried to debug via netstat and my dns, but no luck (not my area of expertise, either).

Edit: same issue holds for anonymous
Edit2: Issue occurs on Ubuntu 21.04, 21.10 and Windows 10, each with a clean new installation of VSCode and the Extension

PS: Love the extension!!! It saved weeks of work!!

**Comment by znck** [comment]
Stale after #232
