### ISSUE TITLE
[Question] Does this work offline?

### ISSUE THREAD

**Issue by felixhao28** [znck/grammarly#213]
I have been using this extension for months and it suddenly occurred to me that my documents and code files might have been sent to Grammarly's server without my consent. For the record, I have not seen or signed any EULA. And I want to confirm that:

1. Does this extension connect to the Grammarly server or the computation is done completely offline?
2. If it connects to the Grammarly server, which kinds of data are sent?
3. Does that require the user's consent? How did this extension implement that part? because I have never seen a EULA pop-up.

Thanks.

**Comment by znck** [comment]
1. This extension connects to Grammarly server.
2. This extension sends text to Grammarly SDK and there after SDK handles as defined in https://developer.grammarly.com/docs/Grammarly-for-Developers-Security.pdf
3. I am not sure if user consent is required or not. Will get back on that.
