### ISSUE TITLE
Pro Account does not connect on Window 10 but does on macOS

### ISSUE THREAD

**Issue by k0nze** [znck/grammarly#216]
I'm using the plugin for some time now. But for three weeks it does not connect to Grammarly anymore on Windows 10. The plugin is installed and shows the spinning icon together with my account email but it won't go further than that. When I log out of Grammarly in VSCode the anonymous connection works immediately but I can't log in again.

I use the same VSCode setup under macOS as well and there are no issues with connecting to Grammarly.

VSCode Version: 1.62.0
Grammarly (unofficial) Version: 0.14.0

**Comment by theluke** [comment]
Same problem here. Win 10

**Comment by efjerb** [comment]
Not really solving the underlying problem here, but this process worked for me:

Log out of Grammarly -> restart VS Code -> log in to Grammarly -> restart VS Code

**Comment by kapooramit** [comment]
Same here. Premium account not working in Windows 10. I am logged in but it cannot detect that.

**Comment by znck** [comment]
Switched to Grammarly SDK which supports account login: https://developer.grammarly.com/docs/connected-accounts#connected-accounts

However, the SDK is missing API to initiate OAuth from nodejs process. (It's coming next week on Tuesday)

**Comment by znck** [comment]
Version 0.18+ support connecting Grammarly premium accounts. Run "Grammarly: Log in" command.
