### ISSUE TITLE
Support customised rules in Grammarly for Business

### ISSUE THREAD

**Issue by theluke** [znck/grammarly#217]
Hello and thank you for the work!

We are evaluating Grammarly for Business for the team, ideally, I want to integrate the Google Style Guide in our custom Grammarly rules.

Is the plugin capable to take the rules and apply them to the content?

**Comment by MarkWoulfeNeo4j** [comment]
@znck was this added? Not sure what 'completed' means exactly and can't see an attached PR or commit.
