### ISSUE TITLE
Consider activating this extension only for specific events

### ISSUE THREAD

**Issue by DonJayamanne** [znck/grammarly#219]
Currently this extension gets activated everytime, even when opening a plain text file.
This results in unnecessary resource usage on end user machines.

Orignally filed here https://github.com/microsoft/vscode/issues/138481

Please could you update the `activationEvents` in `package.json` to activate only when necessary
More information can be found here https://code.visualstudio.com/api/references/activation-events

**Comment by znck** [comment]
Configurable using `grammarly.patterns` and `grammarly.selectors` preferences.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/2596484/167084518-a9fd6941-42ab-4c4a-8899-b6effabe792f.png">
