### ISSUE TITLE
Adding to dictionnary does not work for me

### ISSUE THREAD

**Issue by lgmorand** [znck/grammarly#22]
Whenever I add a new word to dictionnary (user, folder, grammarly), at the next restart of VS Code, new words are not recognized anymore. How can debug to see what happens ?

**Comment by znck** [comment]
You can check and confirm is words are added to the dictionary.

For user dictionary, open VS code settings and search for Grammarly. You would see a list of words:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2596484/72874542-49823180-3d18-11ea-93ff-63cc44ecec6d.png">

For workspace/folder dictionary, there would be a file: `.vscode/settings.json` with key `"grammarly.userWords"`.

For Grammarly dictionary, you can confirm in https://account.grammarly.com/customize.

**Comment by lgmorand** [comment]
Ok, I do confirm that if from the editor, I pick the menu "-> add to grammarly dictionnary" (or user or folder), it does not work, nor appear in the list of words in the settings. (I didn't set user/pwd)

What is weird is that if I had user manually in settings, they stay in the settings but are ignored in the editor (even after restart vscode)


ps: no .vscode/settings.json folder is created


I'm running a standard admin user (not elevated VsCode with UAC), standard folder (not system reserved) and last Win10

**Comment by lgmorand** [comment]
you just close it like it while I confirm it does not work for me ? :)

**Comment by znck** [comment]
It's my bad, I should have explained why I closed the issue.

So the "add to grammarly dictionary" dictionary option would only work when you have a Grammarly account. In d1880edcfaaab2f579ffe57c75869cbbe5ac6ddb, I added a condition to check if user is logged in.


The extension also maintains a local list of valid words where you can using following quick fix actinos.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/2596484/73046781-5f6b3000-3e99-11ea-850f-6c111887e9fd.png">


> I believe this should fix the issue. If it still persists, then the problem is in some other place. We can reopen the issue.

**Comment by lgmorand** [comment]
Thanks, that's now very clear :-) That's why I was expecting for grammarly. I still need to find why add to "user/folder" does not work for me. I'll try on another computer to compare

**Comment by tomaskrulis** [comment]
I have the same issue as the original OP.

MacOS, newest version of the Grammarly extension, free account.

When I run Grammarly: Login, I get a bunch of redirects which I confirmed.

In the end, I get a message in the VSC that I am logged in successfully, however:

- I don't get the option to add a word to the dictionary in the quick-fix menu
- I don't have the "Grammarly:User words" setting in my VS code settings
- If I add the setting manually to `settings.json` they are ignored.

What am I doing wrong and how can I fix that?

**Comment by munsterlander** [comment]
Same issue.  I am logged in, but I do not get the add to personal dictionary option.
