### ISSUE TITLE
Use for LateX

### ISSUE THREAD

**Issue by Igorsmit00** [znck/grammarly#220]
I can't seem to get the extension working in my LaTeX documents. Could this also be included (or could anyone explains where to find it)?
Edit: It seems like it does work when I create a new Tex file but not on my files that already existed

**Comment by znck** [comment]
Latex is not supported yet. Follow https://github.com/znck/grammarly#adding-support-for-new-language if you want to send a PR.

**Comment by thomwiggers** [comment]
For reference, a tree-sitter grammar appears to exist at https://github.com/latex-lsp/tree-sitter-latex
