### ISSUE TITLE
Ignore the incorrect spacing in latex \cite{} 

### ISSUE THREAD

**Issue by wang-ps** [znck/grammarly#224]
Please add options for ignoring the incorrect spacing in latex \cite{} command, as shown below
![image](https://user-images.githubusercontent.com/7525130/147799206-0a0a4d50-985e-487e-87b7-34c1286ce4ea.png)

**Comment by znck** [comment]
Latex is not supported yet. Follow https://github.com/znck/grammarly#adding-support-for-new-language if you want to send a PR.
