### ISSUE TITLE
loading forever

### ISSUE THREAD

**Issue by neuronflow** [znck/grammarly#225]
for some reason the extension stopped working. I am logged into the Grammarly premium account like always, the extension displays a loading icon and nothing happens. no error message. 
I logged out and in again but nothing changes :/

I am aware this is a terrible bug report, sorry.

**Comment by Scott-Thomas** [comment]
Not sure if this will help you, @neuronflow but I had the same issue.
I uninstalled the extension, and deleted the extension folder (in Linux, so ~/.vscode/extensions/znck.grammarly-0.14.0/)
Once I reinstalled the extension and signed back in, it worked again.

**Comment by znck** [comment]
Stale after switching to Grammarly SDK.
