### ISSUE TITLE
Grammarly not updating on Markdown files

### ISSUE THREAD

**Issue by theluke** [znck/grammarly#228]
Hi,
we are using Grammarly for business, we work on VSCode with markdown files.

All the team is using the plugin, we noticed that **Grammarly does not update its suggestions after you change the sentence or manually correct the error**.
If you right-click on the Grammarly issue and apply the `quick fix`, then the issue disappears.

What type of logfile do you need to investigate the problem?

Along the same lines, these are other issues:

1. Suggestions replacements are not available to apply with Quick fix most of the time, when it works it is definitely an exception.
2. When I click on a wrong word or expression, most of the time it shows a YAML file with metadata that it is not really useful for me, it is difficult to know what word to apply. Maybe it is just me that does not know how to use it.
3. With long files it crashes, I can not really define when this happens. But it opens the output terminal section in vsc, with logs like this one (I am not sure this log corresponds to a crash or normal functioning):

```
> 1646919843417 DEBUG  [TextGrammarCheckHost] (756e74) ChangeSet [
>   { ops: [ { retain: 3428 }, { insert: 'h' }, [length]: 2 ] },
>   [length]: 1
> ]
> 1646919843420 DEBUG  [TextGrammarCheckHost] (756e74) [sync] Remote Text: 2483
> 1646919843502 DEBUG  [TextGrammarCheckHost] (756e74) ChangeSet [
>   { ops: [ { retain: 3429 }, { insert: ' ' }, [length]: 2 ] },
>   [length]: 1
> ]
> 1646919843538 DEBUG  [TextGrammarCheckHost] (756e74) [sync] Remote Text: 2484
> 1646919843655 DEBUG  [TextGrammarCheckHost] (756e74) [sync] Remote Text: 2485
```

**Comment by znck** [comment]
There's a new tree-sitter based approach for supporting different languages: https://github.com/znck/grammarly/blob/main/packages/grammarly-languageserver/src/languages/LanguageMarkdown.ts
