### ISSUE TITLE
As a user I want to be able to include another language type to be analyzed in my settings

### ISSUE THREAD

**Issue by sheldonhull** [znck/grammarly#23]
I use `asciidoc` over markdown for my documentation. I'd like an override option that allows me to designate this other file format as able to be parsed for grammar. Not sure of the architecture, so figured I'd ask, as I wasn't able to get anything working by trying this in the diagnostics.

**Comment by znck** [comment]
Only markdown parser implemented yet. Will add asciidoc support next.

**Comment by znck** [comment]
Added `asciidoc`
