### ISSUE TITLE
Add ability to hide warnings per warning code

### ISSUE THREAD

**Issue by donangel** [znck/grammarly#231]
As a user, I'd like to have the ability to add an array of warning codes (in my settings.json), so that I can disable specific warnings by warning code.

The reason for this user story is this warning, but I think such a feature would come in handy in general. For example, the "unnecessary ellipsis" warning/error (Grammarly 37) is also very annoying, if you're used to putting ellipsis here or there.

![image](https://user-images.githubusercontent.com/4919119/166093529-ac84783c-bac2-4b12-adf5-92835836042f.png)

**Comment by znck** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2596484/167083287-7935229b-f109-4905-82e6-48c06912b429.png">

Added in latest version.
