### ISSUE TITLE
Unable to connect to grammarly: auth authentication failed 401 Headers

### ISSUE THREAD

**Issue by hmemcpy** [znck/grammarly#24]
I noticed that the (excellent!) extension stopped working, checking out the log I noticed the following output (slightly redacted):

```
... 
2020-01-28T11:28:12.815Z grammarly:auth authenticating as <username> {
  accept: 'application/json',
  'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
  'content-type': 'application/json',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 ' +
    'Safari/537.36',
  'x-client-type': 'funnel',
  'x-client-version': '1.2.1082',
  'x-container-id': '<some_id>,
  'x-csrf-token': '<some_token>',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  cookie: 'gnar_containrId=some_value; ' +
    'grauth=some_bigger_value; ' +
    'csrf-token=some_token_value'
}

2020-01-28T11:28:13.509Z grammarly:auth authentication failed 401 Headers {
  [Symbol(map)]: [Object: null prototype] {
    date: [ 'Tue, 28 Jan 2020 11:28:13 GMT' ],
    'content-type': [ 'application/json' ],
    'content-length': [ '19' ],
    connection: [ 'close' ],
    'x-frame-options': [ 'DENY' ],
    'x-xss-protection': [ '1; mode=block' ],
    'x-content-type-options': [ 'nosniff' ],
    'content-security-policy': [ "default-src 'none'" ],
    'strict-transport-security': [ 'max-age=31536000' ],
    'cache-control': [ 'max-age=0, no-store, no-cache' ],
    'x-robots-tag': [ 'noindex, nofollow' ]
  }
}
(node:20470) UnhandledPromiseRejectionWarning: Error: Cannot connect to grammarly, no cookie found.
...
```

I made sure that my username and password were correct. Is there anything I can do to diagnose it? Please let me know if I can provide more information

**Comment by znck** [comment]
What is the version number of the extension?

**Comment by hmemcpy** [comment]
Ah yes, sorry! I'm using v0.6.2, vscode: Version: 1.41.1.

Meanwhile, I removed my credentials and the extension is working again.

If that matters, I don't use 2FA on grammarly.

**Comment by znck** [comment]
I have to write a test suite. I am very new to extension development and unit testing is something I haven't figured out yet.

In v0.6.2, I fixed an issue related to auth but now it seems there can be more bugs.

**Question:** Does it make sense to downgrade to free Grammarly API when auth fails?

**Comment by kaarejoergensen** [comment]
I am getting the same error when trying to log in.I  have version 0.6.2 as well.

For my part, I do not think it makes sense to downgrade to the free API if the auth fails, I'd rather (and I don't know anything about vs code extensions) be shown an error, and then given the choice of downgrading. That way I'd know that something is wrong :) 

Other than that I love your extension! It makes writing my thesis so much easier! Thank you for taking the time to develop it, I really appreciate it 👍

**Comment by hmemcpy** [comment]
Yeah, I think downgrading silently isn't a good idea, too surprising. I think an error popup would be best. The only way I even knew something was wrong was looking at the status bar indicator, it showed `0 out of 100`, and clicking on it did nothing. Then I checked the output logs.

**Comment by andrew-codes** [comment]
I have noticed the same issue and originally thought it was due to code in my PR (#50), but it looks like it may have been introduced in 0.62; which is what my PR is based on.

**Comment by andrew-codes** [comment]
After a little digging, I highly suspect the 401 is due to the CAPTCHA requirement when logging in. I found that I was rate-limited while developing #50. Ever since that point, logging via the browser requires me to check that I'm not a robot.

@hmemcpy can you confirm if you see the CAPTCHA screen via logging in with a browser? When you upgrade/when it stops working, does the login flow when using a browser change for you to incorporate a CAPTCHA screen?

**Comment by mwq27** [comment]
When I try to login to my account I see the `Authentication requires captcha` message. I've also confirmed that when I login in the browser I need to do a captcha. Are we not able to login with this extension if we have Premium?

**Comment by andrew-codes** [comment]
@mwq27 I have noticed the same issue. I have gotten around it by logging in via the browser and answering the captcha when it requires it. It will then work, for a while, until you are required to enter captcha again. Not great, but I'm not sure of an easy fix for this.
