### ISSUE TITLE
Correct article usage vs. Remove the article Conflicting Suggestions

### ISSUE THREAD

**Issue by weaponrex** [znck/grammarly#244]
Grammarly in vscode sometimes suggests removing the article, but it suggests adding the article back after quick-fixing. And this on back and forth, so there is always an error.

Example: It resulted in **_an_** out-of-pocket customer response.

I see why either one could be right or wrong, but the Grammarly website finalized to add or remove the article.

**Comment by wachunga** [comment]
Hi @weaponrex could you provide some example text that triggers this?

**Comment by znck** [comment]
> It resulted in an out-of-pocket customer response.
