### ISSUE TITLE
Mark grammar errors as suggestions

### ISSUE THREAD

**Issue by b1zzu** [znck/grammarly#25]
I would like to see my grammar errors as suggestions (underlined in blue) instant of errors (underlined in red), is this possible?

**Comment by NF997** [comment]
Probably the most convenient solution would be a setting that lets the user specify the severity (Hint/Information/Warning/Error) of the diagnostics generated by Grammarly. 
Other plugins, e.g. the official Python plugin, do it this way, too.

**Comment by NF997** [comment]
@znck Thanks a lot for implementing it! 
Would you mind adding it to the documentation/README so that people know how to use the new setting?

**Comment by znck** [comment]
Long day, I’ll add documentation tomorrow.

**Comment by NF997** [comment]
Thanks!
