### ISSUE TITLE
Whether annotated text can be ignored during spell checking?

### ISSUE THREAD

**Issue by CS123n** [znck/grammarly#258]
Whether annotated text can be ignored during spell checking?

**Comment by znck** [comment]
Can you provide an example of annotated text?

**Comment by CS123n** [comment]
For example, I may write some sentences and rewrite them later. Then I get:
```latex
Today, I ... (now)
% Today, I ... (before)
```
I just want to leave a backup for the original version and I do not care about whether there are grammar mistakes in this backup. Is this possible or not?

**Comment by ainar** [comment]
This is the same issue as https://github.com/znck/grammarly/issues/159, which I understand would be addressed in the opposite issue https://github.com/znck/grammarly/issues/17.
I think https://github.com/znck/grammarly/issues/260 may be a way to meet these issues.

Part checking of files seems to be a really awaited feature! @znck do you need specific help for this?

**Comment by ainar** [comment]
https://github.com/znck/grammarly/issues/17#issuecomment-1179287160 It seems so...
