### ISSUE TITLE
"Error: Cannot find module 'node:perf_hooks'"

### ISSUE THREAD

**Issue by PlanBV2** [znck/grammarly#264]
Version 0.14.0 works fine, but every version above throws the error below.
I tried to find a solution, but I do not know anything about Node js, etc..
The extension was installed/updated using the extension manager from VS Code.

`internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'node:perf_hooks'
Require stack:
- c:\Users\xxxxx\.vscode\extensions\znck.grammarly-0.22.0\dist\server\index.node.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at c:\Users\xxxxx\.vscode\extensions\znck.grammarly-0.22.0\dist\server\index.node.js:38:3661
    at c:\Users\xxxxx\.vscode\extensions\znck.grammarly-0.22.0\dist\server\index.node.js:2:245
    at Object.<anonymous> (c:\Users\xxxxx\.vscode\extensions\znck.grammarly-0.22.0\dist\server\index.node.js:64:604)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\xxxxx\\.vscode\\extensions\\znck.grammarly-0.22.0\\dist\\server\\index.node.js'
  ]
}
[Error - 14:24:55] Connection to server got closed. Server will not be restarted.`

**Comment by jcs090218** [comment]
Try upgrade your node version to 16 or above.

Reference: https://github.com/emacs-grammarly/lsp-grammarly/issues/32

**Comment by PlanBV2** [comment]
Thank you for the tip, that sounds reasonable.
Last question, how do I do that to work with vscode? 
"npm -v" and "node -v" did not work in the terminals, so I guess node .js does come with VScode, or the extension itself (?)
I downloaded the latest version from the node js homepage and if I type "node -v" in a cmd/PowerShell it states v16.15.0, but still, the extension does not work.

So, where is the Version the extension is using and how can I update it?

**Comment by jcs090218** [comment]
> I downloaded the latest version from the node js homepage and if I type "node -v" in a cmd/PowerShell it states v16.15.0, but still, the extension does not work.

I think you got it right? Try redownload Grammarly extension so they could get recompiled by the newer version of node.

**Comment by PlanBV2** [comment]
I have uninstalled Grammarly and reinstalled several versions of Grammarly, but the error stays the same. 
Also, the .vsix file from the Extension Marketplace did not work.

Then I tried to clone and compile it by myself, but I struggled with "rollup -c && node scripts/build-web-extension.mjs" cause he doesn't know the command "rollup"...

Maybe a complete reinstallation of VS Code would help, but I'm a bit scared to configure latex, etc. again... and v0.14.0 is working for me... 

But thank you for your help!! If that is a local problem on my PC, the issue can be closed :)

**Comment by jamesone** [comment]
I am on node 16.5 - I had to use the Grammarly version: v0.12.5

**Comment by semaphore-egg** [comment]
Similar problems on ubuntu20.04, node v16.14.0.

**Comment by wico-blei** [comment]
Updating to the latest VS Code version fixed the problem for me.

**Comment by semaphore-egg** [comment]
> Updating to the latest VS Code version fixed the problem for me.

Can I know what is your last bad version?

**Comment by wico-blei** [comment]
> > Updating to the latest VS Code version fixed the problem for me.
> 
> Can I know what is your last bad version?

Code was not updated since February, but I cant tell yout the exact version number since it's not displayed anymore.

**Comment by semaphore-egg** [comment]
> > > Updating to the latest VS Code version fixed the problem for me.
> > 
> > 
> > Can I know what is your last bad version?
> 
> Code was not updated since February, but I cant tell yout the exact version number since it's not displayed anymore.

After updated my vscode to 1.7.0, the errors disappears but the extension (latest, 0.22.1) still do not work. This time the extension seems to crash silently, wired.

**Comment by wico-blei** [comment]
> > > > Updating to the latest VS Code version fixed the problem for me.
> > > 
> > > 
> > > Can I know what is your last bad version?
> > 
> > 
> > Code was not updated since February, but I cant tell yout the exact version number since it's not displayed anymore.
> 
> After updated my vscode to 1.7.0, the errors disappears but the extension (latest, 0.22.1) still do not work. This time the extension seems to crash silently, wired.

Check the output - maybe you didnt sign in to grammarly. 
Solution for me: F1 -> Grammarly: login

**Comment by semaphore-egg** [comment]
> > > > > Updating to the latest VS Code version fixed the problem for me.
> > > > 
> > > > 
> > > > Can I know what is your last bad version?
> > > 
> > > 
> > > Code was not updated since February, but I cant tell yout the exact version number since it's not displayed anymore.
> > 
> > 
> > After updated my vscode to 1.7.0, the errors disappears but the extension (latest, 0.22.1) still do not work. This time the extension seems to crash silently, wired.
> 
> Check the output - maybe you didnt sign in to grammarly. Solution for me: F1 -> Grammarly: login

I manually restart the grammerly language server and it seems works. Although some errors are still there. I have updated my opened issue.
