### ISSUE TITLE
Custom settings stopped working

### ISSUE THREAD

**Issue by jaczkal** [znck/grammarly#269]
Hello @znck, since some update my custom settings in `settings.json` stopped working and configuration is greyed out.

![image](https://user-images.githubusercontent.com/56036748/169899361-fc969279-a247-435a-aad9-81c07bfd22e9.png)

How can I set it? Especially, turning off the passive voice highlighting.

Thanks!

**Comment by znck** [comment]
Use `grammarly.config.suggestions.PassiveVoice` to turn off passive voice suggestions.

**Comment by jaczkal** [comment]
Thanks!
