### ISSUE TITLE
error `file:///Users/feng/dev/node/src/README.md`

### ISSUE THREAD

**Issue by F3n67u** [znck/grammarly#276]
## Reproduce step

1. open https://github.com/nodejs/node/blob/master/src/README.md in vscode
2. open the output of Grammarly, you will see the below log

```log
Ready!
Initialized!
open file:///Users/feng/dev/node/src/README.md
create text checking session for "file:///Users/feng/dev/node/src/README.md" with {
  "documentDialect": "auto-text",
  "documentDomain": "general",
  "suggestions": {
    "ConjunctionAtStartOfSentence": false,
    "Fluency": true,
    "InformalPronounsAcademic": false,
    "MissingSpaces": true,
    "NounStrings": true,
    "NumbersBeginningSentences": true,
    "NumbersZeroThroughTen": true,
    "OxfordComma": false,
    "PassiveVoice": false,
    "PersonFirstLanguage": true,
    "PossiblyBiasedLanguageAgeRelated": true,
    "PossiblyBiasedLanguageDisabilityRelated": true,
    "PossiblyBiasedLanguageFamilyRelated": true,
    "PossiblyBiasedLanguageGenderRelated": true,
    "PossiblyBiasedLanguageHumanRights": true,
    "PossiblyBiasedLanguageHumanRightsRelated": true,
    "PossiblyBiasedLanguageLgbtqiaRelated": true,
    "PossiblyBiasedLanguageRaceEthnicityRelated": true,
    "PossiblyPoliticallyIncorrectLanguage": true,
    "PrepositionAtTheEndOfSentence": false,
    "PunctuationWithQuotation": true,
    "ReadabilityFillerwords": true,
    "ReadabilityTransforms": true,
    "SentenceVariety": true,
    "SpacesSurroundingSlash": true,
    "SplitInfinitive": true,
    "StylisticFragments": false,
    "UnnecessaryEllipses": false,
    "Variety": true,
    "Vocabulary": true
  }
} 
ready file:///Users/feng/dev/node/src/README.md
connecting file:///Users/feng/dev/node/src/README.md
checking file:///Users/feng/dev/node/src/README.md
error file:///Users/feng/dev/node/src/README.md
```

3. check the status bar: connection status is error

<img width="379" alt="image" src="https://user-images.githubusercontent.com/12343178/170806206-e7eaf5e7-ed58-45db-8c4f-60e5d1730544.png">

## Addition info

1. I have no problem when I open https://github.com/nodejs/node/blob/master/README.md
2. I have not modified any settings of Grammarly vscode.
3. I try to bisect: delete half of the document every time and check if the status is still ok, but I cannot narrow down what the problem is. The bisect status is not stable, sometimes it's ok, sometimes it's not ok.

**Comment by mihaiconstantin** [comment]
I have the same here and I have no clue how to debug the cause. I tried the following with no luck:
- different documents
- usual log in and out from Grammarly followed by a restart
- uninstall the extension and manually purge the files from `~/.vscode/extensions`

I am running VS Code

```
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:04.972Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

with Grammarly `v0.22.1`.

**Comment by mihaiconstantin** [comment]
After some more debugging, I think I found what causes it to break in my case. Suppose you have a `markdown` file called `test.md`. The following text works fine:

```markdown
This works.
```

However, the following text seems to break it:

```markdown
# [1]
```

@F3n67u, can you please check if your file contains a similar pattern?

**Comment by F3n67u** [comment]
> After some more debugging, I think I found what causes it to break in my case. Suppose you have a `markdown` file called `test.md`. The following text works fine:
> 
> ```gfm
> This works.
> ```
> 
> However, the following text seems to break it:
> 
> ```gfm
> # [1]
> ```
> 
> @F3n67u, can you please check if your file contains a similar pattern?

I am sure there is no `# [1]` similar pattern in https://github.com/nodejs/node/blob/master/src/README.md.

**Comment by mihaiconstantin** [comment]
@F3n67u, I went through your file and I removed all headings (i.e., all lines starting with `#`) and the connection error was gone. Then I added `#### `Local` handles` and the connection error came back.
