### ISSUE TITLE
Add support for AsciiDoc

### ISSUE THREAD

**Issue by maxipaxi** [znck/grammarly#28]
Ascii doc seems very similar to markdown, so it should be pretty straight forward to get basic functionality. Currently I find myself changing the file type to plain text and back again to get the output from this extension.

**Comment by znck** [comment]
Would appreciate a PR. To support any language, you have make changes in two places.

https://github.com/znck/grammarly/blob/3223ec512c254892685afb058ba635423f515ee8/package.json#L18

https://github.com/znck/grammarly/blob/3223ec512c254892685afb058ba635423f515ee8/src/client/options.ts#L26
