### ISSUE TITLE
Fail to connect to the server (server initialization failed)

### ISSUE THREAD

**Issue by xiaohk** [znck/grammarly#288]
Hello, thanks for this great extension!

Recently I cannot initialize this extension when I open VSCode, which alerts me the following error:

```
[Error - 6:32:27 AM] Server initialization failed.
  Message: Request initialize failed with message: request to https://js.grammarly.com/grammarly-sdk@1.7 failed, reason: getaddrinfo ENOTFOUND js.grammarly.com
  Code: -32603 
[Error - 6:32:27 AM] Starting client failed
  Message: Request initialize failed with message: request to https://js.grammarly.com/grammarly-sdk@1.7 failed, reason: getaddrinfo ENOTFOUND js.grammarly.com
  Code: -32603 
```

I tried to reload and restart VSCode. The error persists, and there is a spinner in my footer showing `Starting Grammarly language server.`

Any suggestion will be appreciated! Thanks!

**Comment by znck** [comment]
Do you use a corporate proxy server?

**Comment by xiaohk** [comment]
I am not using a proxy server. I didn't do anything, but I can connect to the server again now. I guess the problem was due to my network issues?

Does it work you now @TangHengxuan?

**Comment by TangHengxuan** [comment]
It works now! Thank you! The corporate proxy server should not cause service link problems. It's my mistake that I haven't understood the configuration “grammarly.files.include” . 
Thanks again!

**Comment by Karpisek** [comment]
Hi. Im facing the same issue and IT IS caused by the corporate proxy (if I disconnect I don't get any error) if I'm connected to proxy then I get the issue mentioned above.
