### ISSUE TITLE
Authentication with Grammarly fails in Gitpod web

### ISSUE THREAD

**Issue by Siddhant-K-code** [znck/grammarly#310]
The Grammarly extension is already on Open VSX: https://open-vsx.org/extension/znck/grammarly. But authentication with Grammarly fails in Gitpod web, which means you can't use your paid Grammarly plan.

Only works when running Gitpod workspace in local VS Code.

_Originally posted by @maiertech in https://github.com/znck/grammarly/issues/309#issuecomment-1214423930_

**Comment by Siddhant-K-code** [comment]
@maiertech, Any Error you got in VS Code or in Browser Console while Authenticating to it?

**Comment by Siddhant-K-code** [comment]
For Me, While Log In to Grammarly from Gitpod web, it redirected to the following: 
![image](https://user-images.githubusercontent.com/55068936/184550070-cb4b64a8-2c8d-40a8-b394-da0264cfd705.png)

**Comment by Siddhant-K-code** [comment]
Even, after the merge. While login, it is redirecting to this page: 

![image](https://user-images.githubusercontent.com/55068936/184818045-63c36931-73c7-4620-9e6f-3bea6033055c.png)

**Comment by ricardoavelino** [comment]
I have the same issue. Extension version 0.23.9 (pre-released)
