### ISSUE TITLE
Request $/handleOAuthCallbackUri failed with message: Minified error 7

### ISSUE THREAD

**Issue by matskiv** [znck/grammarly#323]
Login fails after redirecting from the browser(Firefox) back into VSCode(Installed on Fedora with snap):

> Request $/handleOAuthCallbackUri failed with message: Minified error #7:  See https://developer.grammarly.com/docs/error-explainer?code=7&trace=Error%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60252%0A++++at+Generator.next+%28%3Canonymous%3E%29%0A++++at+bt+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26642%29%0A++++at+o+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26846%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26907%0A++++at+new+Promise+%28%3Canonymous%3E%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26786%0A++++at+Ve+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60396%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90543%0A++++at+t.SDK.handleOAuthCallback+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90565%29 for details.

Grammarly docs^ say just: `ERROR: #7 Unexpected connect account request.`

**Comment by znck** [comment]
Do you have multiple instances of vscode running?

**Comment by matskiv** [comment]
@znck Yes, that was the cause. I was able to log in successfully after leaving just one VSCode running.
Thank you for this great extension :raised_hands:

**Comment by rahji** [comment]
Getting this error again (it has happened to me before) and I do not have multiple instances of vscode running.
