### ISSUE TITLE
Unable to connect to Grammarly

### ISSUE THREAD

**Issue by ch0rl** [znck/grammarly#350]
### The Error
When I go through the process of connecting to my Grammarly account, after accepting the `xdg-open` request, vscode gives the following error:

```
Request $/handleOAuthCallbackUri failed with message: Minified error #8: See https://developer.grammarly.com/docs/error-explainer?code=8&args=vscode%3A%2F%2Fznck.grammarly%2Fauth%2Fcallback%3FwindowId%3D1&trace=Error%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60282%0A++++at+Generator.next+%28%3Canonymous%3E%29%0A++++at+bt+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26642%29%0A++++at+o+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26846%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26907%0A++++at+new+Promise+%28%3Canonymous%3E%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26786%0A++++at+Ve+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60396%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90543%0A++++at+t.SDK.handleOAuthCallback+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90565%29 for details.
```

The URL referenced gives the error: `Invalid oauth callback url: vscode://znck.grammarly/auth/callback?windowId=1`
The same error happens in both vscode and vscode-insiders. This is using the release version of the extension.

### System Information
This is on Fedora 37.

**Comment by maxwellcui** [comment]
I see the same problem both on Ubuntu 18.04 and Mac Mini M2 chip.

**Comment by chikamichi** [comment]
Confirming it happens within WSL2 (Debian 11). Same error message.

**Comment by Ziyang-Chen2021** [comment]
Confirming it happens on Windows 10, with vscode version 1.75.1 (user setup) with Grammarly extension version 0.22.1

**Comment by enaielei** [comment]
> Confirming it happens on Windows 10, with vscode version 1.75.1 (user setup) with Grammarly extension version 0.22.1

Same.

**Comment by FDUZS** [comment]
same on Windows 11 here

```text
Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎5/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```

**Comment by georgeherbert** [comment]
Can confirm the same issue on M1 Pro MBP.

**Comment by crmelchior** [comment]
Same error. I have found a workaround to get the extension working:
  
Go to the extension page, click the arrow beside Uninstall button, and select "Install Another Version..." Select **v0.18.0**, and reload VSCode. Try going through the process of connecting to your Grammarly account. After connecting successfully, you can update the extension to the latest version.

**Comment by georgeherbert** [comment]
Can confirm that workaround works for me too! Many thanks!

**Comment by KedneckInc** [comment]
> Go to the extension page, click the arrow beside Uninstall button, and select "Install Another Version..." Select **v0.18.0**, and reload VSCode. Try going through the process of connecting to your Grammarly account. After connecting successfully, you can update the extension to the latest version.

The earlier version worked, but updating to the latest version brought back the same error for me.

**Comment by crmelchior** [comment]
> The earlier version worked, but updating to the latest version brought back the same error for me.

For me, after logging in the extension kept working even after updating to the latest version.

**Comment by ch0rl** [comment]
The latest version of the extension works for me so I am closing this issue

**Comment by xenonz95** [comment]
I found that I couldn't log in no matter what after not using the plugin and Grammarly desktop app for a long time (tried rolling back to 0.18 and preview versions), but everything seemed to be normal after I installed the desktop app and logged in. The official version of the plugin can work normally without requiring me to log in. I don't know if my experience is valuable information.
