### ISSUE TITLE
Request $/handleOAuthCallbackUri failed with message: Minified error 8

### ISSUE THREAD

**Issue by rdohms** [znck/grammarly#361]
Explainer links to this [page](https://developer.grammarly.com/docs/error-explainer?code=8&args=vscode%3A%2F%2Fznck.grammarly%2Fauth%2Fcallback%3FwindowId%3D2&trace=Error%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60282%0A++++at+Generator.next+%28%3Canonymous%3E%29%0A++++at+bt+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26642%29%0A++++at+o+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26846%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26907%0A++++at+new+Promise+%28%3Canonymous%3E%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A26786%0A++++at+Ve+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A60396%29%0A++++at+https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90543%0A++++at+t.SDK.handleOAuthCallback+%28https%3A%2F%2Fjs.grammarly.com%2Fgrammarly-sdk%401.7%3A17%3A90565%29)

And it says:
> ERROR: #8
> Invalid oauth callback url: vscode://znck.grammarly/auth/callback?windowId=2

Single instance of VSCode running on latest preview or latest version.

**Comment by znck** [comment]
Fixed in latest prerelease version 0.23.15.
