### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by ozum** [znck/grammarly#379]
Hi,

Thanks for the hard work in providing this plugin, especially considering that Grammarly does not offer any API.

I just installed the extension on VSCode 1.81.0. However, I couldn't use it and got the "Language client is not ready yet" error when I tried to check the spelling.

Can I provide some more information to help to solve this issue?

Kind Regards,

![image](https://github.com/znck/grammarly/assets/1497060/8fdfce6d-b399-431a-b8f2-99d3d27bc690)

**Comment by ozum** [comment]
It started to work without any change on my side.

**Comment by woter1832** [comment]
This is happening to me too.

<img width="971" alt="image" src="https://github.com/znck/grammarly/assets/68354513/74001e0a-9d53-41a8-bacf-9d29d975da00">
