### ISSUE TITLE
Add Word Ability

### ISSUE THREAD

**Issue by ahmadawais** [znck/grammarly#4]
Thanks for the awesome work. I use [SpellRight](https://marketplace.visualstudio.com/items?itemName=ban.spellright) but I love Grammarly. Can you add the ability to `Add a word`. I use 

```json
{
  "key": "ctrl+alt+cmd+w",
  "command": "spellright.addFromSelectionToUserDictionary"
}
```

To add the word to global dictionary.

**Comment by znck** [comment]
Available in v0.3+
