### ISSUE TITLE
Ability to turn check _off_ by default

### ISSUE THREAD

**Issue by eramdam** [znck/grammarly#415]
Maybe it's already possible and I missed an option, but I'd like to be able have the checking be paused until I start it manually. Is that possible?

**Comment by tomasrei** [comment]
+ 1

Or move the notifications to warnings (yellow triangle) instead of errors (red circle).

**Comment by tomasrei** [comment]
> * 1
> 
> Or move the notifications to warnings (yellow triangle) instead of errors (red circle).

Actually, I found that there is a setting at the bottom of the extension settings:

![image](https://github.com/znck/grammarly/assets/50247285/47c34817-5e6c-4288-92fd-5c386c990dca)

Seems like it's working!

**Comment by eramdam** [comment]
Indeed!
