### ISSUE TITLE
Errors never disappear, even after being corrected

### ISSUE THREAD

**Issue by patrys** [znck/grammarly#83]
I am experiencing this odd behavior where the extension correctly highlights issues however the markers (eg. squiggly lines) remain in the document even after an issue is resolved (either by correcting a spelling mistake or adding the word to the ignore list).

As I continue editing the document, the error markers start to drift away from the words they were originally highlighting which leads to further confusion.

VSCode Version: 1.44.0-insider
OS: Darwin x64 19.4.0
File: `*.mdx` (Markdown React) using the [VSCode MDX extension](https://marketplace.visualstudio.com/items?itemName=JounQin.vscode-mdx).

**Comment by aavdberg** [comment]
Yes notice the same

**Comment by jellebakker96** [comment]
I have the same problem but it only happens sometimes

**Comment by hanpari** [comment]
I guess it is a problem related to Grammarly itself because I often experience similar strange behavior on my mobile phone where is no VS Code.

**Comment by hanpari** [comment]
And one more thing. I believe the problem is related to the length of the text. The more characters, the more unpredictable Grammarly becomes, both in VS Code and my mobile Grammarly app. Perhaps it needs a longer timeout.

**Comment by MarcoScaletta** [comment]
@patrys 
May the output log help?
Which is yours?
