### ISSUE TITLE
Doesn't seem to be working on Insiders and on Windows

### ISSUE THREAD

**Issue by pocesar** [znck/grammarly#84]
The extension worked briefly, but now it doesn't seem to be accepting the credentials anymore, always falling back to "asdf" every time the command palette is opened.  the new credentials never stick. where can I delete the saved (wrong) credentials?

**Comment by znck** [comment]
https://support.microsoft.com/en-in/help/4026814/windows-accessing-credential-manager

I’ll add a command to clear credentials.

**Comment by znck** [comment]
Fixed in 250260da3823d9f5b54e09d792d6e623e9e00550
