### ISSUE TITLE
Context menu doesn't show autocorrect for misspelled word

### ISSUE THREAD

**Issue by a0s** [znck/grammarly#88]
Thank you for extension! I found a little problem with it. This extension shows red line under misspelled word, but there is no "fix word" (or something similar) in context menu. Is it right working of the extension? As I know, original Grammarly has correction suggestions.

My platform: MacOS 10.15.3, VSCode 1.44.0, grammarly extension 0.10.0

**Comment by znck** [comment]
An option to fix spelling is provided whenever correct spelling suggestion is available from Grammarly API. There are cases when Grammarly cannot detect intended words and no correction is available. However, if you could provide me with some example words for which there was no "Correct your spelling" action available, I can explore further.
