### ISSUE TITLE
Getting correction error due to captcha

### ISSUE THREAD

**Issue by maxipaxi** [znck/grammarly#89]
After using it for a little while I am getting

    grammarly:auth *****@gmail.com connection failed { error: 'SHOW_CAPTCHA' }

When trying to log-in again I get:
![image](https://user-images.githubusercontent.com/3920594/79240345-f381dd80-7e71-11ea-8bac-9a56dbf83ef2.png)

**Comment by znck** [comment]
Are you on the latest version of the extension? If yes, then it reuses session to minimize the number of authentication requests, hence preventing captcha prompts. Try logging in after an hour or so (I am not sure what is cooldown period for auth API).

I am closing the issue for now, but if it doesn't work, I'll reopen and dig deeper.

**Comment by favoyang** [comment]
I'm using 0.12.1, the SHOW_CAPTCHA error happens frequently.

**Comment by timsueberkrueb** [comment]
This happened to me as well, would it be possible to expose the captcha in the interface somehow?

**Comment by favoyang** [comment]
Well, I guess this just happens because of lacking OAuth API of Grammarly.

**Comment by dexhunter** [comment]
I met the same problem, will try after an hour. Thanks
