### ISSUE TITLE
Silencing Grammarly API errors

### ISSUE THREAD

**Issue by cyberalien** [znck/grammarly#91]
When extension cannot connect to Grammarly API, which happens way too often recently, VSCode shows error in corner and switches to "Output" tab.

Is it possible to silence those errors?

Example of errors:
![grammarly](https://user-images.githubusercontent.com/822287/79327008-6c3d7400-7f1c-11ea-8317-e69fe7e58941.png)

At the same time when those two errors appear, VSCode also switches from "Terminal" to "Output" tab.

**Comment by znck** [comment]
I’ll add a debug option to disable errors.

**Comment by sbyma** [comment]
I see this issue as well. Why are requests failing in the first place? Shouldn't that be fixed, rather than simply suppressing errors?

**Comment by ghuba** [comment]
I am seeing the same error. It shows up somewhat irregularly for markdown files.

![image](https://user-images.githubusercontent.com/4511360/79699175-aff8ec00-8242-11ea-81ec-c1a569e4b599.png)

**Comment by Markyparky56** [comment]
Working with TeX files, happens semi-regularly. Possibly related error from output log:

```
[Error - 23:47:27] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed unexpectedly without providing any details.
  Code: -32603 
```
