### ISSUE TITLE
Add a Tree View Container

### ISSUE THREAD

**Issue by jaguarfi** [znck/grammarly#92]
I think it could be great to have a tree view for this extension to show the Grammarly's report.

**Comment by jaguarfi** [comment]
Do you think something like this is good?. I think it can help to visualise the overall feedback in a more user-friendly manner. I can try to develop it, but I cannot promise anything because I am not an expert. 
![image](https://user-images.githubusercontent.com/10437475/80286027-a6372300-8731-11ea-8b2d-8ce8c3da5593.png)

**Comment by znck** [comment]
I feel it doesn’t provide enough value to block space on sidebar.
