### ISSUE TITLE
Can't login, test username provided

### ISSUE THREAD

**Issue by ALIENQuake** [znck/grammarly#98]
```
celenaski
123456
```
Cannot log in using this test account.

**Comment by sunyongke** [comment]
I still cannot log in with your account

**Comment by sunyongke** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/17466255/89105254-2d431800-d452-11ea-98b1-a8a3d5790606.png">

**Comment by ALIENQuake** [comment]
Well, It appears that grammarly requires email as 'username' ,not actual username.
